### ISSUE TITLE
Debug remote PASOE instances

### ISSUE THREAD

**Issue by gquerret** [vscode-abl/vscode-abl#10]

**Comment by M0rr155** [comment]
Yes, this would be great !!!!

**Comment by gquerret** [comment]
PASOE debugger is available in the pre-release stream.

**Comment by M0rr155** [comment]
Hello Gilles,

I think i am on the releaseview:
[cid:d0623b8b-f871-4730-97aa-bddef86e23d6]

But how to configure to debug an PASOE instance?

Can you point me into the right direction?

Maurice
________________________________
Van: Gilles Querret ***@***.***>
Verzonden: vrijdag 29 maart 2024 14:51
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] Debug remote PASOE instances (Issue #10)


PASOE debugger is available in the pre-release stream.

**Comment by gquerret** [comment]
Images are not visible when you reply by mail.

You have to switch to pre-release from the extension page:
![image](https://github.com/vscode-abl/vscode-abl/assets/6498723/bc1bd407-a066-44b8-9bf5-8f6e1ea12bdf)

Short video of the PASOE debugger
https://raw.githubusercontent.com/vscode-abl/vscode-abl/develop/resources/images/debugger02.webp

**Comment by M0rr155** [comment]
I have this PASOE instance running:
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/86ff6d7f-f2ad-4cb8-b13b-d474b72ccc4f)

and i have this config in launch.json
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/58a347a6-25fb-42a7-a92e-9335362ab36c)

but this is what i get when connecting:
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/740f8c0b-2bd1-4753-83c9-8b2b23c926c7)

**Comment by gquerret** [comment]
Make sure that your PASOE instance is enabled for debugging. Check that everything is working in PDSOE if you can.
The debug console view can also provide information, as well as `$TMP/vscode-debug-adapter.txt`.

**Comment by M0rr155** [comment]
I have made some progress again.
Check my old Eclipse environment to be able to debug: that works.
Now back to mu VSCode environment:
I have this in my launch.json:
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/9a64b78c-ddbb-4125-b035-405a3a4ebb5a)

But i see this error in debug console:
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/4e0ca9e9-efe9-4078-a8c4-484e642b94d7)

**Comment by M0rr155** [comment]
excuse me: this is the error

![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/b9f89032-c3c6-4bcb-9398-f99b88bac4ec)

**Comment by M0rr155** [comment]
But the file is existing...
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/87e7d0be-78f0-4651-9771-e9226e13af5e)

**Comment by M0rr155** [comment]
Ok: some more progress...
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/fa00c50a-d52b-480c-882e-2da0c2a072d6)

but still no stopping on the breakpoints...
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/8f8daf1d-dd01-4a90-9638-93525bf0056e)

**Comment by gquerret** [comment]
Breakpoints depend on rcode being present on disk, so check that they can be found. You can try with a basic procedure first, without any include file.
Also check $TEMP/vscode-debug-adapter.txt ; it will show the location of breakpoints being set.

**Comment by gquerret** [comment]
Conversation could be moved here: https://github.com/vscode-abl/vscode-abl/discussions/134

**Comment by M0rr155** [comment]
And how does the debugger find this R-code? Is that the localRoot setting in the config?

![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/bfab1ff6-b99f-4c36-a884-d0eb7dfe4efe)
