### ISSUE TITLE
Startup procedure:  how about a "pre-startup" procedure?

### ISSUE THREAD

**Issue by kenherring** [vscode-abl/vscode-abl#100]
From the [`README.md`](https://github.com/vscode-abl/vscode-abl/blob/main/README.md#project-configuration): 

```jsonc
  "procedures": [ // List of procedures, started before the main entry point (and after DB connection and propath configuration)
    { "name": "foo/bar.p", "mode": "once" /* Mode can be once, persistent or super */ }
  ],
```

This runs "after DB connection" has been made, but something that would be nice would be to have a procedure that runs before any DB connections are made.  This would specifically be used to update schema.

The current startup does allow for running shell scripts, and I'd want a new pre-startup procedure to have the same ability.  Something like `ant update-dbs` would would either delete and recreate the DBs we're interested in, or possibly incrementally update the schema.

**Comment by gquerret** [comment]
Could be done.
@jmls That may also solve your problem of the LS which is started faster than your DB.

**Comment by gquerret** [comment]
Introduced in 1.4.25: New 'init' mode for procedures started with the language server AVM runtime
