### ISSUE TITLE
Renamed files are not picked up by plugin

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#106]
If a class is renamed in VSCode (F2 in the explorer view) it is not being picked up (everywhere?) by the plugin. The TempTableIndexRangeSizeInfoForm class was renamed to TempTableStatsForm , and also moved into a different location.

I see the compilatione error below, from a .P. Saving the .CLS does not result in a "Compiling" message in the ABL Language Server output.

Retarting VSCode (I did not try restarting the language server ) results in the errors/etc as expected.

![image](https://github.com/vscode-abl/vscode-abl/assets/8291561/1cf47312-0b3b-4edc-9ad1-7f71cf32dd6d)

**Comment by gquerret** [comment]
Tried multiple times, if the language server is running the renames will be handled. Maybe your LS was not running ?
Please reopen if you can reproduce consistently.
