### ISSUE TITLE
Providing an invalid project number to ProEnv crashes panel

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#109]
Open a ProEnv terminal. Enter a value larger than the selection presented. Hit enter and wait for the panel to disappear. Looks like the Terminal crashes and takes the Panel down with it. But dunno.

Using [2023-10-13T12:55:40.733-0400] [INFO] LanguageServerInfo: 1.10.2-8b75a3d -- ClientInfo: Visual Studio Code 1.83.1 .

**Comment by gquerret** [comment]
Fixed in develop branch
