### ISSUE TITLE
Keyword index-information not highlighted

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#111]
Uppercase/lowercase is verified, but the keyword index-information is not colored:

![image](https://github.com/vscode-abl/vscode-abl/assets/13220627/29d0dcca-b384-4dd6-a99b-ad31758a57be)

**Comment by gquerret** [comment]
`index-information` is part of the keyword list that are supposed to be highlighted. It's not hightlighted due to the regexp that control syntax highlight. I won't change that for now, but that will be solved when semantic highlighting is activated in the language server.
