### ISSUE TITLE
Rcode parsing error 

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#114]
As asked, I'm logging this ... apologies for the screenshot, but I can't find that text in any of the logs in the .builder/ directory.

Rename attached rcode [ISupportsAvailable-r.txt](https://github.com/vscode-abl/vscode-abl/files/13641537/ISupportsAvailable-r.txt)

OE version: 12.7
`[2023-12-11T16:33:28.484-0500] [INFO] vscode.rootDir: c:\Users\Peter\.vscode\extensions\riversidesoftware.openedge-abl-lsp-1.4.25\resources`
`[2023-12-11T16:33:28.798-0500] [INFO] LanguageServerInfo: 1.12.0-c089af9 -- ClientInfo: Visual Studio Code 1.85.0` 

![image](https://github.com/vscode-abl/vscode-abl/assets/8291561/6baf1b09-e909-4ac5-a2e5-bb0672e6e4d3)

**Comment by gquerret** [comment]
The file that you submitted is valid, and doesn't throw an exception in my environment. I'll consider that it's bad luck when reading the stream... But reopen an issue if this happens again.
