### ISSUE TITLE
Add ability to add wildcards in a excludesFile

### ISSUE THREAD

**Issue by Bert-CCE** [vscode-abl/vscode-abl#115]
This issue is related to #94.  
We would like the ability to use wildcards in the excludesFile. When the excludes list (where it is allowed) gets too long, we would simply be able to move this to a excludesFile.

This would simplify the maintainability of the file.

Is there is a reason why this is not possible or will not be implemented, feel free to discuss this and close the issue.

**Comment by kenherring** [comment]
This would be useful for me as well.  

Alternative idea:  allow both the "excludes" and "excludesFile" to work simultaneously.  Then I could list directories in the "excludes" and specific files we don't compile in the "excludesFile".

Probably easier to just allow glob patterns in excludesFile lines though.

**Comment by gquerret** [comment]
Added support for includesFile and excludesFile with glob patterns. That will be available in the next pre-release.
