### ISSUE TITLE
Error running command **ABL: Change build mode**

### ISSUE THREAD

**Issue by kenherring** [vscode-abl/vscode-abl#116]
Whenever I try to use the **ABL: Change build mode** command I run into the following error.  Not a huge problem since it's easy to change in the workspace settings, but figured you would want to know about it.

I don't see anything in the logs for this error.

Tested with the current release v1.4.25 and pre-release v1.5.4.

![image](https://github.com/vscode-abl/vscode-abl/assets/3201462/09e2e3a1-384d-4ca5-ba95-b445ce9beb51)

I've seen this on a variety of projects so I'm thinking it will be easy to reproduce, but if not let me know what other information would be helpful and be sure to collect it.

**Comment by gquerret** [comment]
Thanks, that will be fixed in next release !
