### ISSUE TITLE
Code blocks: `If...then do: ... end.` not being recognized as collapsible

### ISSUE THREAD

**Issue by candru05** [vscode-abl/vscode-abl#118]
I'm finding that some code blocks are collapsible, like procedures, methods, for blocks, but that doesn't seem to be the case for an `if ... then do: ... end.` block. You can see from this screenshot that the `method` block and the `repeat` block are collapsible, but there's no option for the `do:` blocks on lines 84 and 92. We have a lot of legacy code with many `if ... then ... else if ... then ...` structures, so it would be handy to have.
Thank you!

![image](https://uploads.linear.app/0095e3bd-1f0f-4e0f-99c7-6559bb746a08/aa3ed5f1-4cb5-4261-96d5-2276fbf6ad1d/9cb0be34-f3be-4a49-a715-733d3775ba78?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAwOTVlM2JkLTFmMGYtNGUwZi05OWM3LTY1NTliYjc0NmEwOC9hYTNlZDVmMS00Y2I1LTQyNjEtOTZkNS0yMjc2ZmJmNmFkMWQvOWNiMGJlMzQtZjNiZS00YTQ5LWE3MTUtNzMzZDM3NzViYTc4IiwiaWF0IjoxNzA2MTEwNjgyLCJleHAiOjMzMjc2NjcwNjgyfQ.PJ3pxUeVJJHiZtmWPsRZ-q3pMKjH928-ljLAo0IzkNc)

**Comment by gquerret** [comment]
Confirmed, that will be implemented.

**Comment by gquerret** [comment]
Done.
