### ISSUE TITLE
Autocomplete suggests table name fields rather than buffer

### ISSUE THREAD

**Issue by danielbecroft** [vscode-abl/vscode-abl#121]
When modifying a field reference, if the autocomplete adds in the table/buffer name again, rather than using what is already there.

Starting code:
```
find first Customer

if Customer.CustNum gt 0 then
    display Customer.CustNum.
```

(1) If I hightlight `CustNum` and delete it (leaving my cursor after the `.`, then the autocomplete options available through Ctrl+Space only shows the field names, and selecting on inserts the field name correctly. 

(2) If I don't delete the `CustNum` text, and instead put my cursor after the `.`, then autocomplete suggests full table+field name options (ie `Customer.Address`, `Customer.Address2`, etc. Selecting one of these inserts the full table name again, so the text becomes:

```
if Customer.Customer.AddressCustNum then
```

It gets more funky when a buffer is being used. Starting with:

```
if bCustomer.CustNum gt 0 then
```

Doing the scenario (2) from above, the buffer isnt suggested first. The default buffer is suggested `Customer.Address`, when I would expect the buffer to be shown first (`bCustomer.Address`)

Everything seems to work better when typing from scratch, but the changes start to cause more issues.

**Comment by gquerret** [comment]
Confirmed, that will be improved.

**Comment by gquerret** [comment]
Fixed in the develop branch, that will land in the pre-release really soon. Don't hesitate to report other issues !
