### ISSUE TITLE
keeping releases up to date

### ISSUE THREAD

**Issue by jmls** [vscode-abl/vscode-abl#122]
version 1.7.1 is available in the official vscode registry
version 1.4.21 is available on the releases page of this repo
version 1.4.23 is available on the open vsix registry 

Please can we have 1.7.1  available in github and open vsix ?

**Comment by gquerret** [comment]
Pushed 1.6.0 to open-vsx.org. 1.7.1 is the latest version in the prerelease stream, which is not supported on open-vsx.

**Comment by jmls** [comment]
Sorry for bringing this up again, but the changelog says 1.8.0 is released, but can't find it anywhere (vscode extensions, open vsx or github ;) ) 

Where can we get this mystical beast from ? 

The changelog in gitpod mentions 1.6.0, 

the changelog on VsCode extensions (https://marketplace.visualstudio.com/items/RiversideSoftware.openedge-abl-lsp/changelog) says 1.8.0 ...

or is 1.8.0 also a prerelease ?

**Comment by gquerret** [comment]
Stable version is 1.6.x. Prerelease is 1.7.x ; changelog is prepared for upcoming 1.8 (which will become the next stable).
