### ISSUE TITLE
Debugger - Watchpoints support

### ISSUE THREAD

**Issue by gquerret** [vscode-abl/vscode-abl#123]
Reactivate support for watchpoints.

**Comment by M0rr155** [comment]
Yes, this is what i have to (i think)

I can see the variables and their values.
But adding a watch for a variable, the watch says "Internal Error"
![image](https://github.com/vscode-abl/vscode-abl/assets/164477200/2cc77e31-72d0-43b1-afab-f563b1107c0a)

**Comment by gquerret** [comment]
Watchpoint support added in 1.9.6
