### ISSUE TITLE
Improve and autoexecute Generate Assembly Catalog

### ISSUE THREAD

**Issue by clement-brodu** [vscode-abl/vscode-abl#126]
Automatically generate Assembly Catalog at startup.

Currently, it's not possible because the generation is too long because of the Openedge Implementation.

I made a new implementation in C# :
https://github.com/clement-brodu/PCTTools

Improvements:

- faster (for my situation, 20s instead of 8min)
- better with Generics Types
- provide protected members
- provide fields
- provide enum values as fields
- provide constructors
- provide event handler types and invoke signatures
- allow to scan only one type or one assembly
- catalog file without default values

The catalog format has some differences with [current AssemblyCatalog Task](https://github.com/Riverside-Software/pct/wiki/AssemblyCatalog).

**Comment by gquerret** [comment]
I'll try to integrate that !

**Comment by gquerret** [comment]
First version merged in pre-release.
