### ISSUE TITLE
Comments not colour-coded correctly inside property getters

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#127]
The comments in line 63 and 108 in the screenshot are not being recognised as comments, leading to the single quotes in those lines being treated as start- and end-quotes

![image](https://uploads.linear.app/0095e3bd-1f0f-4e0f-99c7-6559bb746a08/bc356fb1-75e4-4836-a4ee-d00362f5ca95/d5126ec1-e909-4825-aa93-65a991b0c882?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAwOTVlM2JkLTFmMGYtNGUwZi05OWM3LTY1NTliYjc0NmEwOC9iYzM1NmZiMS03NWU0LTQ4MzYtYTRlZS1kMDAzNjJmNWNhOTUvZDUxMjZlYzEtZTkwOS00ODI1LWFhOTMtNjVhOTkxYjBjODgyIiwiaWF0IjoxNzA5MjgxNTEyLCJleHAiOjMzMjc5ODQxNTEyfQ.ySHNE3HTD1UuAMV_QO84xtESF_qcZ4uIfWaV9KjwFjA)

**Comment by gquerret** [comment]
Confirmed

**Comment by PeterJudgeZA** [comment]
Fixed in the prerelease

**Comment by gquerret** [comment]
Thanks for the fix !
