### ISSUE TITLE
Default file set is not case-insensitive for code extensions

### ISSUE THREAD

**Issue by ntreeby** [vscode-abl/vscode-abl#130]
I recently copied a program into my project (on Windows), and the extension on this program is ".P" and not ".p".  It was copied into a "source" directory.

 VS Code ABL did not pick up this program up to be built/syntax checked (nor when I made a change to it, etc).  As a result, I didn't pick up a compile-time error in this program until I tried to compile it using PCT (were I explicitly tell it not to be case-sensitive).  Only when I changed the extension to ".p", was it picked up by VS Code ABL.

I assume the same would be true of a ".W" vs ".w", ".CLS" vs ".cls", and so on.

Is this something that can be looked at?  I know the workaround is easy now I know about it, but it was still not something I was looking out for and was quite a puzzle.

Thanks.

**Comment by PeterJudgeZA** [comment]
@ntreeby If you go to workspace settings (CTRL-, and select Workspace), search for "associations". This contains the list of extensions that are associated with the ABL extension. You can add the upper-case variants here and things should work better.

You could probably patch [package.json](https://github.com/vscode-abl/vscode-abl/blob/main/package.json) to add the uppercase versions, and then these would automatically be added to the workspace (I think, at least; @gquerret can comment definitively).

**Comment by gquerret** [comment]
I've tried with a sample.P file, and syntax highlight is working, as well as code completion, but not outline view. It looks like only the build step and subsequent ones are missing, so I don't think modifying package.json will change anything.

**Comment by ntreeby** [comment]
I think @PeterJudgeZA has the better suggestion for now.  While this only affected a relatively small project / repo this time, where it was easy to rename a couple of programs by making the extensions lower-case, we have much larger repos that will be affected where it won't be practical to rename every file.

**Comment by gquerret** [comment]
I had a look at the code, it's a very small change in the language server. That will be fixed in next version. Changing file associations won't work in this case, . p and .w are hard-coded (lowercase) in the LS.

**Comment by gquerret** [comment]
Fixed in development branch. Will be available in next pre-release
