### ISSUE TITLE
Includes not shown in outline, despite setting enabled 

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#142]
Despite the setting being enabled for showing includes in the outline,

![grafik](https://uploads.linear.app/0095e3bd-1f0f-4e0f-99c7-6559bb746a08/68649bb1-c486-4e30-9594-d2198b293095/4ba1861c-b4d9-4289-9af7-9fc50ec38534?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAwOTVlM2JkLTFmMGYtNGUwZi05OWM3LTY1NTliYjc0NmEwOC82ODY0OWJiMS1jNDg2LTRlMzAtOTU5NC1kMjE5OGIyOTMwOTUvNGJhMTg2MWMtYjRkOS00Mjg5LTlhZjctOWZjNTBlYzM4NTM0IiwiaWF0IjoxNzEyNzI3NDYyLCJleHAiOjMzMjgzMjg3NDYyfQ.MjNRotgVFO3SSzqkgFrAKJ9bjLbzh-FGDiI2EiaZAaU)

The outline looks like this for classes

![grafik](https://uploads.linear.app/0095e3bd-1f0f-4e0f-99c7-6559bb746a08/6341107d-8710-4301-acc3-dfbfbee9a3dc/f96d4c6f-bbaf-45c9-8ac7-86b12774afa9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAwOTVlM2JkLTFmMGYtNGUwZi05OWM3LTY1NTliYjc0NmEwOC82MzQxMTA3ZC04NzEwLTQzMDEtYWNjMy1kZmJmYmVlOWEzZGMvZjk2ZDRjNmYtYmJhZi00NWM5LThhYzctODZiMTI3NzRhZmE5IiwiaWF0IjoxNzEyNzI3NDYyLCJleHAiOjMzMjgzMjg3NDYyfQ.AyQzYoK9WL7l35S27NaFhoUO9o1WmbrFhXuxDyS18f4)

**Comment by gquerret** [comment]
Confirmed. The option is there, but it doesn't do anything…

**Comment by PeterJudgeZA** [comment]
So you'll close this as "working as designed" 😄 ?
________________________________

**Comment by gquerret** [comment]
Fixed in dev
