### ISSUE TITLE
Better handling of methods in includes

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#143]
If I have a class that contains some methods, as well an include, and the include has members (methods in this case), all of the members are nicely shown in the outline view, as below 

![grafik](https://github.com/vscode-abl/vscode-abl/assets/8291561/0e24947e-8d71-4d92-81ab-2d0ce20b771a)

However, clicking on MethodA - which is defined in the include - in the outline doesn't do anything. It would be nice if the include was opened in the editor, and the method selected, or something similar.

This might be better once  #142 is resolved.

**Comment by gquerret** [comment]
It's unfortunalely not possible to do that, as the symbols have a range but no file location in the [language server specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentSymbol).
