### ISSUE TITLE
LS crashes when missing dumpFile/schemaFile property

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#144]
If the dumpFile / schemaFile property is missing from a database connection, then the LS crashes on startup.  The attached openedge-properties.json file is quite simple, and crashes every time. LS log attached.

Setting the value of the property to an empty string causes no problems. Setting it to `null` also results in the crash.

This is in the 1.9.1 pre-release. 

Occasionally, when connecting via -H/-S with -U and -P parameters , there is *no* LS log data generated . I can't reproduce that reliably but it happens often enough.

[openedge-project.json](https://github.com/vscode-abl/vscode-abl/files/14951628/openedge-project.json)

[6-ABL Language Server.log](https://github.com/vscode-abl/vscode-abl/files/14951649/6-ABL.Language.Server.log)

**Comment by gquerret** [comment]
Fixed in develop
