### ISSUE TITLE
Change the icon for include files to something less generic

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#146]
Since the 1.9.2 prerelease, includes show up in the outline. The icon used to represent them is a generic 'file' icon . They don't really represent (to me) an include, just a ... something.

![image](https://uploads.linear.app/0095e3bd-1f0f-4e0f-99c7-6559bb746a08/3fe2c9c0-a144-4441-8d7a-4ea43de974ee/72f90ec8-9391-4c24-a050-eda86a397c37?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAwOTVlM2JkLTFmMGYtNGUwZi05OWM3LTY1NTliYjc0NmEwOC8zZmUyYzljMC1hMTQ0LTQ0NDEtOGQ3YS00ZWE0M2RlOTc0ZWUvNzJmOTBlYzgtOTM5MS00YzI0LWEwNTAtZWRhODZhMzk3YzM3IiwiaWF0IjoxNzE0MTk5NjAyLCJleHAiOjMzMjg0NzU5NjAyfQ.K0Sqbl0eh5frlA7GmUu8jKk7MrfyFu4F_3-qjAuSnyw)

The other icons in the outline are more varied. Curly braces mean "include" to ABL , so maybe something like the below could work, with or without the 'file box' around it.

![image](https://uploads.linear.app/0095e3bd-1f0f-4e0f-99c7-6559bb746a08/4ee6b1c4-0753-4219-b44b-455cf80ceeec/bf84dd9a-6074-4d90-a623-3470700003f6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAwOTVlM2JkLTFmMGYtNGUwZi05OWM3LTY1NTliYjc0NmEwOC80ZWU2YjFjNC0wNzUzLTQyMTktYjQ0Yi00NTVjZjgwY2VlZWMvYmY4NGRkOWEtNjA3NC00ZDkwLWE2MjMtMzQ3MDcwMDAwM2Y2IiwiaWF0IjoxNzE0MTk5NjAyLCJleHAiOjMzMjg0NzU5NjAyfQ.7zoaxSesPx2CBPljAQgYayWVjgLioWnfOvUBYB5Ur3Q)

**Comment by gquerret** [comment]
Two problems here:
* Include file is not part of the default symbol kinds: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolKind
* An ABL theme would be required to show a different icon

ABL is not the only language where extra symbol kinds would be needed, but it seems there's no clean / standard solution to do that for now.

**Comment by PeterJudgeZA** [comment]
Pity.

How does the (default?) JSON outline show `{}` and `[]` ? I'd take the curly braces for include.

Since you post that link ... how about static and abstract symbols for ABL methods/classes?

**Comment by gquerret** [comment]
> How does the (default?) JSON outline show {} and [] ? I'd take the curly braces for include.

That's a very good question !

**Comment by gquerret** [comment]
Both `Namespace` and `Object` are represented as curly braces. I'll try using `Namespace`, but the problem is that different themes can choose to represent it differently. Let's see…
