### ISSUE TITLE
Custom java executable path for language server not being used

### ISSUE THREAD

**Issue by danielbecroft** [vscode-abl/vscode-abl#147]
I've specified a custom path for the java.exe using the `abl.langServerJavaExecutable`, and this was working. But recently it seems the value is being ignored. Our Software Restriction Policies are pretty strict, and it appears that the Language Server is still attempting to launch the `java.exe` from the users' profile:

```
Access to %USERPROFILE%\.vscode\extensions\riversidesoftware.openedge-abl-lsp-1.9.2win32-x64\jre\bin\java.exe has been restricted by your Administrator by the default software restriction policy level.
```

Has the value for this path changed, or been dropped? I've tested under 1.8.1, 1.8.2 and 1.9.2 (pre-release).

**Comment by gquerret** [comment]
JRE is now bundled with the extension (so no issues would be raised by incompatible version of JVM being in the `PATH`). The `abl.langServerJavaExecutable` is still there, but only used when the JRE is not found in the extension (there are now OS specific builds of the extension). I agree that it still should be possible to override the JVM being used, that will be available in next pre-release.

**Comment by gquerret** [comment]
Fixed  in 1.9.3

**Comment by gquerret** [comment]
Note that the extension will soon switch to Java 21.

**Comment by danielbecroft** [comment]
Thanks @gquerret . I can confirm 1.9.3 works correctly.
