### ISSUE TITLE
Blank/empty "includes" property in source path should default to the default

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#148]
LanguageServerInfo: 1.14.0-ad14939 -- ClientInfo: Visual Studio Code 1.89.1 -- JVM: Eclipse Adoptium 17.0.11+9

The context help says that the "includes" property defaults to **/*.p etc. 
![grafik](https://github.com/vscode-abl/vscode-abl/assets/8291561/f1ea39bc-797d-4ac8-b1f9-e0c992f96edd)

However, if the property value is empty/blank, then this default is not applied (ie nothing is compiled).

**Comment by gquerret** [comment]
Will be available in next release
