### ISSUE TITLE
Formally support custom settings in openedge-project.json

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#15]
openedge-project.json contains a lot of config-settings we already have elsewhere or need in the near future

- DB's
- startup parameters
- propath & source directories

So I would like to establish that file as a more complete config-file for our dev-tooling. For that I would need to 

- rely on current structure to be stable
- by able/allowed to add my own properties, e.g. in a "smartComponentLibrary" property

**Comment by gquerret** [comment]
See discussion #20

**Comment by gquerret** [comment]
Done
