### ISSUE TITLE
Project named same as another project + "test" does not run prog with correct propath

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#150]
```
vscode.rootDir: c:\Users\Peter\.vscode\extensions\riversidesoftware.openedge-abl-lsp-1.9.5-win32-x64\resources
LanguageServerInfo: 1.15.0-SNAPSHOT-c1ca9bf -- ClientInfo: Visual Studio Code 1.89.1 -- JVM: Eclipse Adoptium 17.0.11+9
```

I have 3 projects in a workspace
* <root>/abl 
* <root>/abltest 
* <root>/noprefixtest

I have a program in the abltest folder , test.p. This program simply displays PROPATH.  When I run using F2, the propath from the abl/ project is shown, not the correct one for abltest/ 

This works just fine if the program is run from the noprrefixtest folder.

The workspace and projects are attached. There's no default project configured.

[vscode-temp.zip](https://github.com/vscode-abl/vscode-abl/files/15394602/vscode-temp.zip)

**Comment by gquerret** [comment]
Fixed in next pre-release.
