### ISSUE TITLE
Folder remains red (emphasized) in explorer after renaming class with error.

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#153]
Steps to reproduce:

- create class "MyTestClass" in a folder
- add class block, so that file compiles
- change class name in class block, causes compile-error as .cls file name and class name do no longer match
- rename cls file to match the new class name
- compile error on the file is gone
- folder still in red with tooltip "Contains emphasized items"

https://github.com/vscode-abl/vscode-abl/assets/13220627/6a3f8e4f-4992-49f0-805e-85e65550ded7

Restarting the language server resolves the issue.

**Comment by gquerret** [comment]
Confirmed. I'll check why the diagnostics are not removed when file is renamed.
