### ISSUE TITLE
Table and Field name completion is not working

### ISSUE THREAD

**Issue by darrenparr** [vscode-abl/vscode-abl#156]
I don't know if this a consequence of a recent update but table and field name completion seems to be broken. I have valid DF files against my databases and they are connected OK. The DF files are valid and OK.

Typing a table name like "StyleMaster." does not produce a field list. On another attempt I got a field list after about 10 seconds or so. Mostly it does not work at all. Temp-tables are completing OK. So if I define a temp-table like the above database table then this is fast and produces a list of fields quickly.

There is the following line in the language server output. I don't know if this is relevant.

Jun 10, 2024 2:39:39 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 284

**Comment by gquerret** [comment]
To verify if table list is broken in LS, create a new file, and type `FIND ` then Ctrl + Space. You should get the table list.
Long response time can happen at LS startup. The warning that you see is just that some messages were not delivered to the LS.
