### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by darrenparr** [vscode-abl/vscode-abl#158]
I've been using this non stop for quite a few weeks and have come across some issues and don't know if they are specific to me but I'll list them anyway.

1. I get mutiple issues starting openedge process with error 13, unable to create lbi..... Its normally when starting a task but can also be exhibited when starting the LS.

```
[2024-07-04T10:31:45.462+0100] [ERROR] ### OE Client #0 ended with exit code 2 ###
[2024-07-04T10:31:45.465+0100] [ERROR] ### OE Client #0 standard output can be found in c:\VSCODE\ERPHOME\.builder\stdout0.log
[2024-07-04T10:31:45.466+0100] [ERROR] ### OE Client #0 log file can be found in c:\VSCODE\ERPHOME\.builder\clientlog0.log
```
stdout0.log says
```
Unable to open or create c:\VSCODE\ERPHOME\.builder\tmp\lbia07876, error 13. (354)
```
If I restart the LS its fine normally. This happens all the time and also when compiling so I have to restart the LS on each occassion. I get this with an "ant build" every now and again too but again a restart sorts it. It looks like VSCode is interfering with openedge. 

2. The default cabl-rules highlight the use of a backslash which is valid. For example when using file-info:file-name on a windows os and trying to parse file-info:full-pathname. Is there any way to turn this off?

3. Lots of issues with not being able to open the current buffer with prowin or using shift-f8 to open with appbuilder. I have to restart vscode to get it to correctly know my buffer is an openedge buffer. The error I get is one stating "current buffer doesn't belong to any OE project". Restarting the LS does not fix this.

4. I seem to get a lot of java errors regarding ummatched cancellation notifications. Looks like an issue but don't know if its anything I should worry about.

**Comment by gquerret** [comment]
1. Error 13 is for "Permission denied", so you should check for other processes (antivirus or other kind of security tools) preventing you from creating files. 
2. You can control rules in `.vscode/cabl.json`
3. Does the file really belong to a project ? And is your project initialized correctly ?
4. That happens when the LS doesn't answer quickly enough, and the client sends another request cancelling the previous one. A few cancellation notifications is not a problem.

**Comment by gquerret** [comment]
Is this issue still relevant ?
