### ISSUE TITLE
Enhancement request : Visual feedback of successful compile

### ISSUE THREAD

**Issue by ccecvb** [vscode-abl/vscode-abl#161]
Maybe I'm old school, but one thing I'm missing when editing ABL code in VsCode is a visual feedback of successful compile.

I think it would be nice if
1. successful compile of the currently edited file was shown on the status bar
2. An ABL check syntax command existed that would show a dialog with "Syntax OK" or the compilation error

I know I can find the compile result in ABL Language server log output, and maybe I should just learn to keep that log open.

**Comment by mikefechner** [comment]
I usually look at the "Problems" view filtered by the active file only.

**Comment by kenherring** [comment]
The tab of the editor changes color depending on status.  Red means a failed compile.  It also has a count of the number of warnings/problems.

**Comment by ccecvb** [comment]
Thank you for the suggestions, I'll try them.

Found another use-case for check syntax.

Check syntax should ignore that a source is excluded from build, then it can be used to check if a source that is excluded would compile.

**Comment by ccecvb** [comment]
Found that `ABL compile current buffer`  does a check compile regardless of the exclude status of a source so it is equivalent to check syntax.

I'll close the issue
