### ISSUE TITLE
Removed source is shown as "source was not found (293)" error

### ISSUE THREAD

**Issue by ccecvb** [vscode-abl/vscode-abl#162]
I moved  a source that did not compile to a directory outside of the propath.
Now the previous source location is shown as an error 293

![image](https://github.com/user-attachments/assets/7fc639a7-a13e-4054-a06f-6ef477136f09)

Rebuild project did not remove the error.

**Comment by mikefechner** [comment]
Does restart language server help?

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
From: ccecvb ***@***.***>
Sent: Wednesday, July 17, 2024 7:52:38 AM
To: vscode-abl/vscode-abl ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vscode-abl/vscode-abl] Removed source is shown as "source was not found (293)" error (Issue #162)


I moved a source that did not compile to a directory outside of the propath.
Now the previous source location is shown as an error 293

image.png (view on web)<https://github.com/user-attachments/assets/7fc639a7-a13e-4054-a06f-6ef477136f09>

Rebuild project did not remove the error.

**Comment by ccecvb** [comment]
Fixed by restart language server
