### ISSUE TITLE
Profile vs Built in functions

### ISSUE THREAD

**Issue by Kenney-code** [vscode-abl/vscode-abl#168]
When setting up multiple profiles, the rebuild project and run with _progres/prowin are still using the default profile although the profile is correctly set in the profile.json found in the .vscode directory.
This is with vscode running on Windows. I have yet to test it in a Linux environment.
[profile.json](https://github.com/user-attachments/files/16387262/profile.json)
![Capture](https://github.com/user-attachments/assets/ae255e37-e96b-4314-99e8-80485bcbf6bf)
```json
{
  "name": "test",
  "graphicalMode": false,
  "oeversion":"11.7",
  "profiles": [
  {
    "name": "GUI",
    "inherits": "default",
    "value": { "graphicalMode": true }
  },
  {
    "name": "upgrade",
    "inherits": "default",
    "value": { "graphicalMode": true, "oeversion": "12.8" }
  }
  ]
}
```
buildpath is setup differently for all profiles.

If it is compiled without the rebuild projects but by buildMode it works as expected.

**Comment by Kenney-code** [comment]
Current workaround is by building with ant scripts, but since there is a native function I was wondering.

**Comment by gquerret** [comment]
I confirm that this is the case. Propath & DB connections should match current profile.
However, I recommend working with VS Code tasks if you want to start your application.

**Comment by gquerret** [comment]
Fixed in develop branch, that will be available in next prerelease
