### ISSUE TITLE
NEW- Causes Source Code Highlighting Issues

### ISSUE THREAD

**Issue by coopert1787** [vscode-abl/vscode-abl#173]
This may not be the proper place for this, as I am using the Riverside Software Extension, but here goes.

Here is a code sample:

```
define variable new-data as integer no-undo.
define variable check-value as logical no-undo.

assign
  new-data = 12345
  check-value = true.

if (check-value = true) then
  message "Yes" view-as alert-box.
```

![Screenshot 2024-08-15 131717](https://github.com/user-attachments/assets/886747b9-11ab-42e5-a62d-5811d97000a4)

Any other additional code between the `new-` and some other set of characters that "terminates" this coloring, is highlighted/colored incorrectly for the reserved words, etc.  As can bee seen in the pic.  In this case, it appears to be beginning parentheses.  Not 100% sure of other "terminating" characters.

**Comment by gquerret** [comment]
> This may not be the proper place for this, as I am using the Riverside Software Extension, but here goes.

This repository is the home of the Riverside Software extension, no problem opening issues here.

**Comment by coopert1787** [comment]
And another, something with "with down".

Code Snippet:

define variable a as character no-undo.

form
  a at 15
  skip()
  with down# down row 12 no-labels no-box frame f-body.


PIC:
![image](https://github.com/user-attachments/assets/50cb4b00-9309-4aed-be13-184ed652e252)

**Comment by coopert1787** [comment]
Might be no language server set up, local installation only.  Been searching for something to tweak.

**Comment by PeterJudgeZA** [comment]
@coopert1787 The highlighting does come from the extension (as @gquerret mentioned) but not from the language server (by default) . The extension currently uses the [VS Code Syntax Highlighting](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) , as opposed to semantic highlighiting (which would come from the language server). I know there has been some work done on semantic highlighting but it's not the default behaviour.

Tweaks don't exist for the current syntax highlighting grammar. You have to modify the grammar itself, and contribute your updates back to the [abl-tmlanguage project](https://github.com/chriscamicas/abl-tmlanguage/) .
