### ISSUE TITLE
Debugger does not display variables after step over remote call

### ISSUE THREAD

**Issue by ccecvb** [vscode-abl/vscode-abl#174]
Debugger does not display variables after step over remote call.
The issue can occur with step into as well, but I get it more consistently with step over.

* Vscode 1.92.2 over ssh to RHEL server
* OpenEdge ABL v1.9.23 (pre-release)

### screenshot before step over
![image](https://github.com/user-attachments/assets/89b5a316-9ecb-41a6-8e7e-b25a07e68d7f)

### screenshot after step over
**Note that the line in the call stack is no longer selected. **
After manually selecting the line the variables are shown.

![image](https://github.com/user-attachments/assets/58391785-1d8a-40c7-808f-d7027552a4b6)

**Comment by gquerret** [comment]
I did a quick test, and didn't run into any issue. It will be easier to investigate with traces. Can you enable "Debug Adapter Debug" and "Debug Adapter Trace" in the extension settings ?
![image](https://github.com/user-attachments/assets/872e02c9-c4c7-4a72-9c9a-93ff016c5a31)


Then execute the debugger session, and send me the files generated by the Debug Adapter.

**Comment by ccecvb** [comment]
@gquerret I had to terminate some java processes holding my debug port and restarted the language server.
Now I cannot reproduce this anymore.
I'll close the issue and re-open if I can provide more details

**Comment by M0rr155** [comment]
I have a problem with a for each within a for each:
Values of fields of the table of the first for each are showing, but values of the fields of the second table are not showing.
See the attach
![ErcRlagkKp](https://github.com/user-attachments/assets/7c85c237-aa0b-4bfe-963c-066cdb0b0f6c)
ed file

**Comment by gquerret** [comment]
@M0rr155 Please open a new issue, that issue was closed and is on a different topic.
Do you see the values in the buffer list (in the variables view, just about the watch view) ?

**Comment by M0rr155** [comment]
[vscode-debug-adapter.txt](https://github.com/user-attachments/files/16833803/vscode-debug-adapter.txt)
[vscode-debug-adapter-trace.txt](https://github.com/user-attachments/files/16833806/vscode-debug-adapter-trace.txt)
