### ISSUE TITLE
FUNCTION and PROCEDURE symbols for breadcrumbs and outline

### ISSUE THREAD

**Issue by FSGCorp** [vscode-abl/vscode-abl#175]
Disclaimer: Long time progress programmer but somewhat new to VS Code.
I have racked my brain for two days trying to figure out how to make progress keywords FUNCTION and PROCEDURE (upper or lower case) show up in the breadcrumbs and/or the outline pane and unable to find anything. I assume there needs to be "sybmols" defined but can find absolutely no way to do this. Any help or point in the right direction would be greatly appreciated. I use UltraEdit and it has a easy way to configure and navigate to a function or procedure which is very handy and trying to duplicate this functionality in vscode. It simply lists these in a side-pane and you can dbl-click a name to navigate to it.

**Comment by mikefechner** [comment]
Do you have an openedge-project.json file configured? https://github.com/vscode-abl/vscode-abl?tab=readme-ov-file#project-configuration

Do you see something like this in the status bar of VS Code? 

![image](https://github.com/user-attachments/assets/45771d34-2452-4399-a44f-2863a544401e)

**Comment by PeterJudgeZA** [comment]
If the program compiles, then the outline should contain the procedures, functions, variables and includes for the program in the Outline View.

That can only happen if you have configured the project as Mike suggests.

**Comment by gquerret** [comment]
You can also have a look at [the configuration checklist](https://github.com/vscode-abl/vscode-abl#configuration-checklist).

**Comment by PeterJudgeZA** [comment]
> Additional thought - the syntax highlighting and autocomplete actually do work w/o OE, just not the breadcumbs and outline displaying the functions and procedures, etc.

Yeah, that's expected, at least the highlighting. The autocomplete is "just words" without the language server though - it not really context-aware.

If you choose "Off" for the Editor: Word Based Suggestions you can see what I mean.
