### ISSUE TITLE
File compiles but no outline

### ISSUE THREAD

**Issue by M0rr155** [vscode-abl/vscode-abl#177]
In a new project everyting loads as suspected, no errors in output ABL Language serevr.
I did all the checks.

TestMS.p compiles but shows no outline.

What am I missing?

```
MESSAGE "Main" VIEW-As ALERT-BOX INFO.

RUN SubProcedure.


PROCEDURE SubProcedure:

    MESSAGE "Sub" VIEW-As ALERT-BOX INFO.

END PROCEDURE.
```

**Comment by M0rr155** [comment]
![QQKY81n3vg](https://github.com/user-attachments/assets/ee9da175-bcb2-402f-8677-25e35ffaf16c)

**Comment by gquerret** [comment]
Does the file belong to a source directory (in openedge-project.json) ?

**Comment by M0rr155** [comment]
It is in c:\VSCode\MSTools.



Groeten,

Maurice
________________________________
Van: Gilles Querret ***@***.***>
Verzonden: maandag 26 augustus 2024 10:30
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] File compiles but no outline (Issue #177)


Does the file belong to a source directory (in openedge-project.json) ?

**Comment by gquerret** [comment]
But how did you define the build path in openedge-project.json ?

**Comment by M0rr155** [comment]
i added the file so you could see


Groeten,

Maurice
________________________________
Van: Gilles Querret ***@***.***>
Verzonden: maandag 26 augustus 2024 11:06
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] File compiles but no outline (Issue #177)


But how did you define the build path in openedge-project.json ?

**Comment by gquerret** [comment]
You can't attach files here by email.

**Comment by M0rr155** [comment]
[openedge-project.json](https://github.com/user-attachments/files/16746764/openedge-project.json)
Here's the file.
Everything is compiling correctly, but no outline

**Comment by gquerret** [comment]
Are you sure the project is correctly initialized ? You have an absolute path name in your `source` entry, I'm really not sure this works as you'd expect.  Check the first lines of the language server output.

**Comment by M0rr155** [comment]
Ok, what path should it be? Relative from the place my openedge-project.json is in (same as the workspace-dir) ?

My workspace directory is C:\VSCode\MSTools and there is also my openedge-project.json.
What should i put then in these entries?

      {
            "type": "source",
            "path": "C:/VSCode/MSTools",
            "build": "C:/VSCode/MSTools/build",
            "excludes": "build"
        },
        {
            "type": "propath",
            "path": "C:/VSCode/MSTools"
        },


Greetings,

Maurice
________________________________
Van: Gilles Querret ***@***.***>
Verzonden: maandag 26 augustus 2024 18:12
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] File compiles but no outline (Issue #177)


Are you sure the project is correctly initialized ? You have an absolute path name in your source entry, I'm really not sure this works as you'd expect. Check the first lines of the language server output.

**Comment by gquerret** [comment]
All paths are resolved from the directory where openedge-project.json is located. So you can use
```
      {
            "type": "source",
            "path": ".",
            "build": "build",
            "excludes": "build"
        },

```

**Comment by gquerret** [comment]
No need to repeat the propath entry with the same directory, all source entries are automatically added as propath entries

**Comment by M0rr155** [comment]
Yes, with the "." used it works great again!
Thanks for your help (and amazing work making this extension) !

Groeten,

Maurice
________________________________
Van: Gilles Querret ***@***.***>
Verzonden: dinsdag 27 augustus 2024 09:10
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] File compiles but no outline (Issue #177)


No need to repeat the propath entry with the same directory, all source entries are automatically added as propath entries
