### ISSUE TITLE
Branches and build errors

### ISSUE THREAD

**Issue by M0rr155** [vscode-abl/vscode-abl#182]
When switching branches (from branch A to B) i get build errors on files (classes etc) that are renamed or otherways not available (new created in branch A) in the new actual branch (branch B).

When closing VSCode and restart it then the build errors on the new actual branch (branch B) are gone.

Is there a setting that can help me or is this something that has to be solved in the plugin?

**Comment by gquerret** [comment]
This is supposed to be fixed (in #153). Can you just confirm you're using the latest version of the plugin ?

**Comment by M0rr155** [comment]
I see this: v1.11.0 (pre-release)


________________________________
Van: Gilles Querret ***@***.***>
Verzonden: dinsdag 3 september 2024 21:46
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] Branches and build errors (Issue #182)


This is supposed to be fixed (in #153<https://github.com/vscode-abl/vscode-abl/issues/153>). Can you just confirm you're using the latest version of the plugin ?
