### ISSUE TITLE
Question - any difference in functionality/performance of using sources vs r-code/pl as dependency?

### ISSUE THREAD

**Issue by LievenDeFoor** [vscode-abl/vscode-abl#188]
Hi Gilles,
Forgot to ask you: is there any difference in functionality or performance in using r-code/pl-files as "propath" buildPath entry versus using sources (as "source" buildPath entry)?
For sources you're able to generate xref and parse the actual source code, whereas for r-code you're left with only that...
Thanks,
Lieven

**Comment by cverbiest** [comment]
I guess that when debugging you would not be able to step through that code.
I wonder if the debugger would/could use debug-listing files if those were available.

**Comment by gquerret** [comment]
Propath entries only need rcode / PL, no parsing is done even if source code is found in the directory. That's enough to have the required symbols for code completion, but Javadoc will be missing (unless you provide the JSON file in the `documentation` attribute).

Source entries are monitored, and changes trigger a compilation. Javadoc documentation is handled during the compilation.

**Comment by gquerret** [comment]
> I wonder if the debugger would/could use debug-listing files if those were available.

That's not the case. The aim is to work with versioned dependencies, with source artifacts being available. In this case, the source code would be extracted on the fly.
