### ISSUE TITLE
Write the version of the grammer being used by the extension somewhere

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#191]
It would be nice to have the version of the grammar in use to be written into a log somewhere.
It would be useful to be able to troubleshoot issues in the syntax highlighting.

**Comment by gquerret** [comment]
Good idea, I'll add that.

**Comment by gquerret** [comment]
Grammar version number is written in the "ABL" log output:
![image](https://github.com/user-attachments/assets/ced2a4b7-6dd4-43e9-9a50-609266686686)
