### ISSUE TITLE
Multiple "ABL Language Server" entries in Output dropdown when restarting ABL Language server

### ISSUE THREAD

**Issue by LievenDeFoor** [vscode-abl/vscode-abl#194]
![image](https://github.com/user-attachments/assets/0caf8b78-6a84-4244-90ec-85b1f18f4056)

Looks like this only happens for one project in the workspace though...

**Comment by gquerret** [comment]
This was already improved a few weeks (but it happened more frequently). This can still happen if VS Code detects a modification on the LS output **after** having restarted it, but I can't do anything about it unfortunately.
