### ISSUE TITLE
Collapse USING statements block

### ISSUE THREAD

**Issue by gquerret** [vscode-abl/vscode-abl#200]
The block of USING statements should be hidden (collapsed) by default.

**Comment by mikefechner** [comment]
By default means, there will be an option to turn this off, right? I am really not fan of that.

**Comment by gquerret** [comment]
Controlled by `editor.foldingImportsByDefault`
![image](https://github.com/user-attachments/assets/2fddd67d-9300-48c8-ab0a-33228582c9f6)

**Comment by gquerret** [comment]
@LievenDeFoor Fixed
@mikefechner GLobal setting in VS Code, that won't change the default behavior

**Comment by mikefechner** [comment]
Thx
