### ISSUE TITLE
Proparse errors in ABL Language Server output

### ISSUE THREAD

**Issue by LievenDeFoor** [vscode-abl/vscode-abl#205]
We're seeing a couple of Proparse errors in the ABL Language Server output.
I'll make separate issues for those that I assume are different issues.

`[2024-09-10T09:18:51.101+0200] [ERROR] [Glims] Proparse error in 'be\mips\ablframework\reports\AbstractXmlReportProcessingData.cls' at position C:\Workspace\glimsdev128-vscode\Glims\mate-abl-sources\man\inc\ds_ReportLog.i:11:34`

ds_ReportLog.i is included like this:
    `{ ds_ReportLog.i &ACCESS=PRIVATE &SERIALIZABLE=SERIALIZABLE}`

and contains:

```
&SCOPED-DEFINE ACCESS {&ACCESS}
&SCOPED-DEFINE REFERENCE-ONLY {&REFERENCE-ONLY}
&SCOPED-DEFINE SERIALIZABLE {&SERIALIZABLE}

DEFINE {&ACCESS} {&SERIALIZABLE} TEMP-TABLE w_ReportLogEntry NO-UNDO {&REFERENCE-ONLY}
    FIELD wrlge_Id AS INT64
    FIELD wrlge_Severity AS INTEGER
    FIELD wrlge_Content AS CHARACTER
    INDEX wrlge_Id IS UNIQUE PRIMARY wrlge_Id.

DEFINE {&ACCESS} {&SERIALIZABLE} DATASET ds_ReportLog {&REFERENCE-ONLY}
    FOR w_ReportLogEntry.
```

I believe the "11:34" corresponds to the start of the word "DATASET" in the line `DEFINE {&ACCESS} {&SERIALIZABLE} DATASET ds_ReportLog {&REFERENCE-ONLY}`

**Comment by LievenDeFoor** [comment]
I've seen the same error for this line in another file, so I can only assume proparse doesn't like serializable datasets...
TestSerializable.cls:

```
BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Serializable.TestSerializable SERIALIZABLE:

    DEFINE PRIVATE SERIALIZABLE TEMP-TABLE w_TempTableName NO-UNDO
        FIELD FieldName AS INTEGER
        INDEX FieldName IS PRIMARY UNIQUE FieldName.

    DEFINE SERIALIZABLE DATASET ds_Test FOR w_TempTableName.

END CLASS.
```
```
[2024-09-10T11:55:29.306+0200] [ERROR] [Glims] Proparse error in 'Serializable\TestSerializable.cls' at position :9:25
[2024-09-10T11:55:29.306+0200] [INFO] [Glims] Compilation successful: Serializable\TestSerializable.cls
```
It seems to have no problem with the SERIALIZABLE TEMP-TABLE though...

**Comment by gquerret** [comment]
Moving issue to Proparse repository: Riverside-Software/sonar-openedge#1141
