### ISSUE TITLE
Proparse error on preprocessor constant in InitializeComponent method

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#206]
A colleague has adjusted Visual Designer generated code in InitializeComponent to use a preprocessor constant instead of a hard coded value.
While this is against the internal rules (as this will break when changing anything using the Visual Designer), the preprocessor and compiler has no problem with this.
I do however get proparse errors on this, and I don't see how this differs from any other use of preprocessor constants.

![image](https://github.com/user-attachments/assets/6df5d617-d361-49f1-b513-c3ef738ede7e)

`[2024-09-10T11:08:24.318+0200] [ERROR] [Glims] Proparse error in 'be\mips\glims\client\qc\view\windows\QCPopulationView.cls' at position :1897:79`

Position 79 appears to be the . after the closing } in the screenshot above...

The same in OEDT editor looks like this:

![image](https://github.com/user-attachments/assets/1ddfc41a-3a45-4069-99ed-777a5ac1b93d)

Any idea why Proparse can't handle this?

**Comment by LievenDeFoor** [comment]
Yes!
It's in an include file, inside a
`&IF '{&WINDOW-SYSTEM}' = 'MS-WINDOWS'`
block.
I remember this is something we discussed (WindowSystem=MS-WINDOWS is in progress.ini).
So this is a known limitation which could be solved if we could inject this value into the preprocessor somehow...

**Comment by stefandrissen** [comment]
The [window-system](https://docs.progress.com/bundle/openedge-abl-reference-122/page/Preprocessor-name-reference.html) preprocessor is set by whatever .exe is being used - prowin vs _progres - does your openedge-project.json config contain:
````
"graphicalMode": true
````
?

**Comment by gquerret** [comment]
@stefandrissen Proparse doesn't rely on the AVM, so some values are hard-coded. It's possible to override them in sonar-scanner: https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list#preprocessor--proparse. This is currently not possible in VS Code (but not for long).

**Comment by gquerret** [comment]
@LievenDeFoor Added `preprocessor` section in openedge-project.json in order to control various preprocessor values. Will be available in next pre-release.

**Comment by LievenDeFoor** [comment]
@stefandrissen , the value of SESSION:WINDOW-SYSTEM / {&WINDOW-SYSTEM} can be overridden, which is what we use to get a consistent value on Windows.

> ABL supports an override option that enables applications that need the WINDOW-SYSTEM attribute to return the value of "MS-WINDOWS" for all Microsoft operating systems to do so. To establish this override capability, define the WindowSystem key in the Startup section in the current environment, which might be the registry or an initialization file. If the WindowSystem key is located, the WINDOW-SYSTEM attribute returns the value associated with the WindowSystem key on all platforms. 

https://documentation.progress.com/output/ua/OpenEdge_latest/pdsoe/PLUGINS_ROOT/com.openedge.pdt.langref.help/rfi1424920468946.html

**Comment by gquerret** [comment]
Version 1.11.2 is now on the marketplace (or will be soon). You can use the `preprocessor` section in opendge-project.json to control some preprocessor values in Proparse. Feedback welcome :-)

**Comment by lievendf** [comment]
> Version 1.11.2 is now on the marketplace (or will be soon). You can use the `preprocessor` section in opendge-project.json to control some preprocessor values in Proparse. Feedback welcome :-)

Can you give an example on the syntax to be used (e.g. to set the WINDOW-SYSTEM)?

**Comment by gquerret** [comment]
@lievendf Here is an example:
```
  "preprocessor": {
    "windowSystem": "MS-TRUC",
    "batchMode": false
  }
```

You can use code completion in the config file.

**Comment by lievendf** [comment]
@gquerret , thanks, we figured out some things by looking that the last commits on the develop branch ;-)
I noticed you use "windows" and "unix" for the opsys variable, but the documentation states the possible values are "UNIX" and "WIN32".
I verified "WIN32" is indeed the value returned when using OPSYS or "{&OPSYS}"

**Comment by gquerret** [comment]
When using `windows`, opsys and {&opsys} will return WIN32. I'll update the documentation.
