### ISSUE TITLE
FP for Class name and Package name casing 

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#21]
Not reported in SQ on the server or in PDSOE, but in VSCode:

![image](https://user-images.githubusercontent.com/13220627/161482729-538e2845-b636-406d-beb4-492c5859832a.png)

**Comment by mikefechner** [comment]
Found a new case - not reported in Sonarlint in PDSOE:

![2022-10-19_14h11_02](https://user-images.githubusercontent.com/13220627/196687312-2fe64a35-b513-48bd-82bc-a89519a4edcf.png)

**Comment by gquerret** [comment]
Fixed. Will be available in the next version.
