### ISSUE TITLE
"Run with prowin" - contains "-basekey ini" and "-ininame" twice

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#212]
I'm launching a "Run with prowin" through CTRL-SHIFT-P -> ABL: Run with prowin and noticed the following command line output:

`Run with prowin - Command line: C:\Progress\OE128\bin\prowin.exe -clientlog c:\Workspace\glimsdev128-vscode\Glims\.builder\rungui.log -p c:\Users\lievendf\.vscode\extensions\riversidesoftware.openedge-abl-lsp-1.11.1-win32-x64\resources\abl-src\dynrun.p -param C:\Users\lievendf\AppData\Local\Temp\rungui-c63c65f4ec929f026fe6f1b5d3bf8da4.json -basekey INI -ininame c:\Users\lievendf\.vscode\extensions\riversidesoftware.openedge-abl-lsp-1.11.1-win32-x64\resources\abl-src\empty.ini -basekey ini -ininame progress.compile.ini -checkdbe -assemblies assemblies -inp 40000 -tok 4000 -noroutineinwhere -D 5000`

It looks like -basekey ini and -ininame are added twice: once by the plugin and once from my "extraParameters".
empty.ini doesn't appear to be empty though...
I assume the AVM only uses the last occurrence of the -ininame startup parameter.

**Comment by gquerret** [comment]
Yes, the plugin always inject its own empty.ini (which is not really empty, but just the default values and NoSplash=yes). You can override this INI file using extraParameters.
