### ISSUE TITLE
Go to definition (F12) 

### ISSUE THREAD

**Issue by dominickdm** [vscode-abl/vscode-abl#214]
When you press F12 or right-click and select ‘Go to definition,’ the message 'No definition found' appears. I was expecting the cursor to move directly to the method.

Example class:
![image](https://github.com/user-attachments/assets/35e71d35-1b98-4dc2-92f4-87c20a32fb52)

Example procedure:
![image](https://github.com/user-attachments/assets/4e71edf0-7e88-4149-b361-bc65103efce6)

The strange thing is that the last example (procedure) seems to work fine for a colleague. What could explain this?

**Comment by cverbiest** [comment]
try close & re-open source, see Gilles comment in #170

**Comment by dominickdm** [comment]
Hello Carl,
Thank you for the suggestion.
I tried to close all open buffers, close VSC, reopen VSC, reopen the testClass.cls and test.p, but it's still not working.

The outline looks fine in both cases:
![image](https://github.com/user-attachments/assets/a7bd736b-4c48-40d3-977d-c4228761e40b)
![image](https://github.com/user-attachments/assets/de96bbcd-49de-408c-ab0c-0265299cc05c)

**Comment by gquerret** [comment]
#1 is for now expected, and will be fixed.

#2 is not expected, and can not be reproduced on this small example. Do you consistently reproduce in your env ? Is your procedure part of a `source` directory ?

**Comment by gquerret** [comment]
Improved definition entrypoint in current pre-release. F12 is supposed to work correctly with method calls (local or from another class). RCode has to be present in the propath.

Attributes and constructors will be added in future pre-releases.
