### ISSUE TITLE
Too many events, it may be wise to restart the builder

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#216]
I'm doing some tests to see the difference in compilation time using numThreads = 4 vs 8.
VSCode is open while I delete 20000+ r-files from Explorer.
Should VSCode notice this and start recompiling automatically?
The only thing I saw was a "Too many events, it may be wise to restart the builder" line in the ABL Language Server output.
After restarting VSCode (I could probably just have restarted the language server) compilation of the sources started as expected.

Edit: I noticed no performance improvement going from 4 to 8 threads (where 3 threads crashed during compilation). Could there be another limiting factor, e.g. a network connection to local databases.

**Comment by gquerret** [comment]
Switching the number of threads requires a LS restart. Then you can execute action "Rebuild project", so you don't have to manually delete the rcode. The notification "Too many events" is thrown when the OS is not able (or willing) to send all events to the subscribers. The message recommends to restart the language server, but in fact a project rebuild is a better solution.

**Comment by gquerret** [comment]
> Edit: I noticed no performance improvement going from 4 to 8 threads (where 3 threads crashed during compilation). Could there be another limiting factor, e.g. a network connection to local databases.

Check process explorer. Usually, the limiting factor is disk I/O. You should also check your antivirus software, they can sometimes consume a crazy amount of CPU, or slow down I/O.
