### ISSUE TITLE
Go to definition of preprocessor constant

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#218]
Go to definition (F12) should work for preprocessor constants too.
Now you just get "No definition found for '<name>'".
OEDT shows the underlying value of the preprocessor constant as well as where (in what file) it is defined when you hover the mouse over it. A ctrl+click takes you to the definition (line) in the file.

![image](https://github.com/user-attachments/assets/c26469bf-ac4b-4539-8da3-8b396ac1abd6)

**Comment by gquerret** [comment]
Not top priority as a minor change to Proparse will be required, but that will be added.

**Comment by gquerret** [comment]
I just noticed that "Go to definition" on preprocessor constants works for me. Is procedure part of a source directory ?

Hover doesn't show anything though.

**Comment by lievendf** [comment]
Yes, the sources involved (.p, .i, .cls) are all part of source entries in buildPath.

**Comment by gquerret** [comment]
Value of preprocessor variable is now displayed in hover entrypoint. That doesn't work for now with the `DEFINED` function, and that requires a change in Proparse, so it will be implemented later. Another ticket keeps track of this change request.

Change will be available in the 1.17.x pre-releases.
