### ISSUE TITLE
FP for commented out code

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#22]
This is reported in VS Code - but not on the SQ web page or in PDSOE:

![image](https://user-images.githubusercontent.com/13220627/161897841-062eac23-ef4b-4a65-af4c-2a4a28edaaf3.png)

**Comment by gquerret** [comment]
What is the value of the parameter ?

**Comment by mikefechner** [comment]
How is that relevant? Which keyword is "Windows" ? How can that be source code? 

Here's the part from cabl.json.

```
    {
      "name": "CommentedOutCode",
      "class": "eu.rssw.antlr.proparse.checks.CommentedOutCode",
      "parameters": [
        {
          "name": "minTokens",
          "value": 0
        },
        {
          "name": "ignoreSingleLineComments",
          "value": true
        },
        {
          "name": "ignoreJavadocComments",
          "value": true
        }
      ]
    },

```

**Comment by gquerret** [comment]
The parser is executed on the content of the comment, but without the last layers where variable names are recognized. In this case, `Windows` is recognized as an ID token, which in turn is recognized as an expression statement with a single Token.
That's the reason why there's an attribute to control the minimum number of tokens in this rule.

**Comment by mikefechner** [comment]
Why isn't this reported withing SQ?

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mikefechner** [comment]
> Because the minTokens attribute has a different value in your quality profile ?

Confirmed. Sorry for missing that.
