### ISSUE TITLE
Out Of Memory crashes

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#223]
![image](https://github.com/user-attachments/assets/63e63a8a-7697-432a-8411-7ac75dc289d5)

Any hints on how to investigate the cause of this?
Just had it happen twice after adding an extra project to my workspace (now 7 in total)...

**Comment by cverbiest** [comment]
This might help https://stackoverflow.com/questions/71614897/vscode-crashed-reason-oom-code-536870904

**Comment by lievendf** [comment]
It looks like the OEUnit project I've recently added is causing the issues...
I'll exclude it from my workspace and use a pl file instead and see how that goes.

**Comment by lievendf** [comment]
Started a rebuild of my project, and meanwhile attempted to open a markdown file...
![image](https://github.com/user-attachments/assets/5bf938ae-847a-451b-b9ef-e4a50869fe74)

**Comment by lievendf** [comment]
I have disabled the "Markdown All in One" extension I was also using and I have the impression this is helping...
Closing this one again, will reopen if the issue reoccurs (without other extensions).
