### ISSUE TITLE
Question: do .pl or .r changes in buildPath entries of type propath trigger recompilation of dependencies?

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#225]
Hi,

Title says it all really.
We have project dependencies that can be pl files or directories with r files.
These are added as "propath" entries in openedge-project.json.
When these change, does that trigger a recompile of the depending sources in the current project?

Thanks,
Lieven

**Comment by PeterJudgeZA** [comment]
PEr @gquerret 's comment at https://github.com/vscode-abl/vscode-abl/issues/188#issuecomment-2337386663 , I believe it's only "source" path types that are monitored.

**Comment by gquerret** [comment]
Current status is that rcode is monitored in propath entries, and method signatures are refreshed from the new rcode, but that doesn't trigger a recompile. Not sure about PL files, I'd say it's the same behavior, but I have to check the implementation. I agree that new rcode should trigger recompile of the child classes.

**Comment by gquerret** [comment]
RCode changes in propath entries now trigger recompile of source code entries which depends on those classes / includes.

PL files are currently not monitored, that will be implemented in a second step.

**Comment by gquerret** [comment]
Changes will be included 1.13.5
