### ISSUE TITLE
Debugger content of variables with minus (-) in name is not shown

### ISSUE THREAD

**Issue by ccecvb** [vscode-abl/vscode-abl#226]
Variable I-NAME is not recognized as a variable, the contents of I are shown

![image](https://github.com/user-attachments/assets/8a336433-23f1-4457-9681-41c60b458784)

VsCode ABL version v1.13.1 (pre-release)
Running on RHEL linux

**Comment by gquerret** [comment]
Confirmed, this happens in all environment. You can view the content of the variable in the debugger panel, but this is not visible when hovering the variable. It looks like the word separator characters configured in the extension are not taken into account by the debugger.

**Comment by cverbiest** [comment]
same goes for buffers that contain -

**Comment by gquerret** [comment]
That's a VS Code issue. Unfortunately, it probably will never be fixed.

* [https://github.com/microsoft/vscode/issues/78073](https://github.com/microsoft/vscode/issues/78073)
* [https://github.com/microsoft/vscode/issues/24520](https://github.com/microsoft/vscode/issues/24520)
* [https://github.com/microsoft/vscode/issues/87790](https://github.com/microsoft/vscode/issues/87790)
* and others…
