### ISSUE TITLE
Sonarlint on linux not working 

### ISSUE THREAD

**Issue by ccecvb** [vscode-abl/vscode-abl#228]
Hi Gilles,

I have a similar setup on windows & linux.

On windows sonarlint is operational
On linux it does not detect any violations.

As a test I introduce an unused variable in a source.

I'll send mail containg the full sonarlint output

**Comment by ccecvb** [comment]
@gquerret Some status updates.
sonarlint seems to be working, but it is very slow

`[Info - 11:54:26.537] Analysis detected 8 issues and 0 Security Hotspots in 4939664ms
`
![image](https://github.com/user-attachments/assets/2eacdeef-793a-4942-aeb0-8bcfdc5bf817)

after removing the last line & saving

![image](https://github.com/user-attachments/assets/2f7b1fd6-5afe-44cb-9fb8-262dbf02448e)

I'll mail a trimmed log

I was not yet on the lastest build of the

**Comment by ccecvb** [comment]
[Info - 15:49:17.391] Analysis detected 7 issues and 0 Security Hotspots in 2148990ms

htop shows sonarlint process is very busy

![image](https://github.com/user-attachments/assets/e8c3bca6-c0f5-4c2f-ad98-e1a943aac214)

Tried the https://github.com/async-profiler/async-profiler on that process
In my first 60 second sample getting git attributes was the most costly operation.

```
          ns  percent  samples  top
  ----------  -------  -------  ---
   474582355    7.90%        3  org.eclipse.jgit.util.FS_POSIX.getAttributes
   430104810    7.16%       43  G1ParScanThreadState::trim_queue_to_threshold
   404220297    6.73%        3  java.lang.ThreadLocal$ThreadLocalMap.getEntryAfterMiss
   360104199    6.00%       36  G1BlockOffsetTablePart::forward_to_block_containing_addr_slow
   270644179    4.51%       19  java.lang.StringLatin1.lastIndexOf
   252628082    4.21%        2  java.io.File.<init>
   242611739    4.04%        1  sun.nio.fs.UnixNativeDispatcher.lstat0
   240085445    4.00%       24  OtherRegionsTable::add_reference
   220058344    3.66%       22  void OopOopIterateDispatch<G1ConcurrentRefineOopClosure>::Table::oop_oop_iterate<InstanceKlass, narrowOop>
   200469356    3.34%        2  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<1335398ul, G1BarrierSet>, (AccessInternal::BarrierType)1, 1335398ul>::oop_access_barrier
   190188571    3.17%       18  sun.nio.cs.UTF_8$Encoder.encodeBufferLoop
   181210230    3.02%        3  jni_SetLongField
   170023673    2.83%       17  void OopOopIterateDispatch<G1CMOopClosure>::Table::oop_oop_iterate<InstanceKlass, narrowOop>
   141402592    2.35%        1  sun.nio.fs.UnixPath.normalizeAndCheck
   130082706    2.17%       13  .annobin__ZN17G1ScanCardClosure11do_oop_workI9narrowOopEEvPT_.start
   121342116    2.02%        1  vtable stub
   121286790    2.02%        1  statx
   110629654    1.84%        1  __GI___close_nocancel
    90006415    1.50%        9  .annobin__ZN19G1RebuildRemSetTask32G1RebuildRemSetHeapRegionClosure14do_heap_regionEP10HeapRegion.start

```

2nd sampe

```
          ns  percent  samples  top
  ----------  -------  -------  ---
   342403879    6.99%        8  sun.nio.cs.UTF_8$Decoder.decodeLoop
   332281162    6.78%        9  org.eclipse.jgit.ignore.IgnoreNode.checkIgnored
   282145310    5.76%        1  statx
   231544912    4.72%        3  java.util.Arrays.fill
   211546736    4.32%        2  org.eclipse.jgit.util.Paths.coreCompare
   191260094    3.90%        3  java.lang.ThreadLocal.setInitialValue
   171253314    3.49%        2  java.nio.Buffer.nextPutIndex
   171046089    3.49%        5  java.util.HashMap.putVal
   161003908    3.28%        2  _int_malloc
   160919207    3.28%        4  java.lang.StringLatin1.hashCode
   141071237    2.88%        1  java.lang.StringLatin1.charAt
   140955390    2.88%        4  org.eclipse.jgit.treewalk.WorkingTreeIterator.isDirectoryIgnored
   120838219    2.47%        1  TypeArrayKlass::allocate_common
   120787188    2.46%        1  jbyte_disjoint_arraycopy_avx3
   120753271    2.46%        3  JNU_NewStringPlatform
   110538448    2.26%        1  __xstat
   100794565    2.06%        3  java.nio.ByteBuffer.wrap

```

**Comment by ccecvb** [comment]
I enabled kernel symbols, looking a another sample

some things about following sample puzzle me, I'm not a kernel or java developer so I could be reading the traces wrong.

* why is the network, vmxnet3, involved org.eclipse.jgit.util.FS_POSIX.getAttributes
* I also see smb2 but everything is on local virtual disks
* I'm not interested in blame info, if it proves to be such a costly operation, can I disable sonarlint getting git blame info ?


```
--- 404247997 ns (14.93%), 40 samples
  [ 0] vmxnet3_tq_xmit.constprop.0?[vmxnet3]_[k]
  [ 1] dev_hard_start_xmit_[k]
  [ 2] sch_direct_xmit_[k]
  [ 3] __dev_xmit_skb_[k]
  [ 4] __dev_queue_xmit_[k]
  [ 5] ip_finish_output2_[k]
  [ 6] __ip_queue_xmit_[k]
  [ 7] __tcp_transmit_skb_[k]
  [ 8] tcp_write_xmit_[k]
  [ 9] __tcp_push_pending_frames_[k]
  [10] tcp_sock_set_cork_[k]
  [11] __smb_send_rqst?[cifs]_[k]
  [12] compound_send_recv?[cifs]_[k]
  [13] smb2_compound_op?[cifs]_[k]
  [14] smb2_query_path_info?[cifs]_[k]
  [15] cifs_get_inode_info?[cifs]_[k]
  [16] cifs_revalidate_dentry_attr?[cifs]_[k]
  [17] cifs_revalidate_dentry?[cifs]_[k]
  [18] cifs_d_revalidate?[cifs]_[k]
  [19] lookup_fast_[k]
  [20] walk_component_[k]
  [21] path_lookupat_[k]
  [22] filename_lookup_[k]
  [23] vfs_statx_[k]
  [24] do_statx_[k]
  [25] __x64_sys_statx_[k]
  [26] do_syscall_64_[k]
  [27] entry_SYSCALL_64_after_hwframe_[k]
  [28] statx
  [29] sun.nio.fs.UnixNativeDispatcher.lstat0
  [30] sun.nio.fs.UnixNativeDispatcher.lstat
  [31] sun.nio.fs.UnixFileAttributes.get
  [32] sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes
  [33] sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes
  [34] org.eclipse.jgit.util.FileUtils.getFileAttributesPosix
  [35] org.eclipse.jgit.util.FS_POSIX.getAttributes
  [36] org.eclipse.jgit.treewalk.FileTreeIterator$FileEntry.<init>
  [37] org.eclipse.jgit.util.FS.list
  [38] org.eclipse.jgit.treewalk.FileTreeIterator.entries
  [39] org.eclipse.jgit.treewalk.FileTreeIterator.<init>
  [40] org.eclipse.jgit.treewalk.FileTreeIterator.enterSubtree
  [41] org.eclipse.jgit.treewalk.FileTreeIterator.createSubtreeIterator
  [42] org.eclipse.jgit.treewalk.AbstractTreeIterator.createSubtreeIterator
  [43] org.eclipse.jgit.treewalk.TreeWalk.enterSubtree
  [44] org.eclipse.jgit.treewalk.TreeWalk.next
  [45] org.sonar.scm.git.blame.GraphNodeFactory.createForWorkingDir
  [46] org.sonar.scm.git.blame.BlameGenerator.prepareStartCommit
  [47] org.sonar.scm.git.blame.BlameGenerator.generateBlame
  [48] org.sonar.scm.git.blame.RepositoryBlameCommand.call
  [49] org.sonarsource.sonarlint.core.commons.util.git.GitUtils.blameWithFilesGitCommand
  [50] org.sonarsource.sonarlint.core.tracking.TrackingService.getIntroductionDateProvider

```

**Comment by gquerret** [comment]
I did multiple tests with various applications attached to local and remote SQ instances. I've noticed a couple times that http fetch errors happened during SonarLint startup, leading to unresponsive extension. That was always related to OutOfMemoryException on the server side. Can you check if you find such exceptions on your SonarQube server ?

Regarding vmxnet3, I assume that this is coming from the project refresh at startup (and websockets scanning for new events).
Re `git blame`, I'll have a look

**Comment by ccecvb** [comment]
@gquerret I found errors similar to this one.

sonar.log:2024.10.04 13:58:05 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[COMPUTE_ENGINE] from [/opt/sonarqube-9.9.1.69595]: /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-3.0.1.el9_1.x86_64/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/var/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Dcom.redhat.fips=false -Xmx1024m -Xms256m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-9.9.1.69595.jar:/opt/sonarqube-9.9.1.69595/lib/jdbc/postgresql/postgresql-42.5.1.jar org.sonar.ce.app.CeServer /var/sonarqube/temp/sq-process12100488391063924470properties

**Comment by gquerret** [comment]
> @gquerret I found errors similar to this one.

That's just a switch on the startup commandline.

**Comment by gquerret** [comment]
Removing the call to `git blame` [here](https://github.com/Riverside-Software/sonarlint-core/blob/OEWhiteList-10.7/backend/core/src/main/java/org/sonarsource/sonarlint/core/tracking/TrackingService.java#L269) solves the problem in this environment.
Will check with SonarSource.

**Comment by gquerret** [comment]
Cause was that a Git repository was in the root directory (i.e. `/.git/`), turning the entire filesystem into a giant work directory when executing `git blame`. Removing the `.git` directory fixed the issue.
