### ISSUE TITLE
Add support for environment variables in abl.configuration.runtimes.path

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#229]
I tried the following but the language server no longer started:

```
"abl.configuration.runtimes": [
    {
        "name": "12.2",
        "default": false,
        "path": "${env:DLC122}"
    },
    {
        "name": "12.8",
        "default": true,
        "path": "${env:DLC128}"
    }
],
```

It would be useful if this was supported.

**Comment by gquerret** [comment]
I really doubt I'll be able to change this standard VS Code behavior !

**Comment by gquerret** [comment]
Won't fix.

**Comment by lievendf** [comment]
@gquerret , wouldn't this just need to get handled on the extension side? When you read the value and it appears to start with ${env: then it's an environment variable which can probably be read by some api call?

**Comment by gquerret** [comment]
This is read by VS Code itself, which doesn't expand `env` values.
