### ISSUE TITLE
False positives on case error:

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#230]
This time with ABL http client (OpenEdge.Net.pl). Get method and OK enum member indicated as case issue:

![image](https://github.com/user-attachments/assets/66b6c7ad-223d-40e6-8337-a5f257dfa5c4)

But

![image](https://github.com/user-attachments/assets/dc56d3e3-e0e8-409c-967e-78b41bf7a2b4)

and

![image](https://github.com/user-attachments/assets/711bc402-0333-4b69-a8af-c3770993b9d7)

**Comment by gquerret** [comment]
Regression introduced in 1.12 (typeInfo caches were not regenerated). Will be fixed in 1.13.3

**Comment by mikefechner** [comment]
Looks like it was fixed with yesterday's pre-release (one of them).

**Comment by gquerret** [comment]
👍
