### ISSUE TITLE
ABL Language server

### ISSUE THREAD

**Issue by luciansrb** [vscode-abl/vscode-abl#231]
Hi,

Working with a remote session on a linux server, I'm having some issues with the Language server giving me an error at startup.

"OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000082000000, 2147483648, 0) failed; error='Not enough space' (errno=12)
[Info  - 9:52:04 AM] Connection to server got closed. Server will restart."

I am not sure if there is any way to go around it as I do not have access to the server configuration.

Thanks

**Comment by gquerret** [comment]
Looks like the JVM is not able to allocate enough memory at startup. Check if you can start a Java process on the server side, and / or  ask your system administrator how much memory is available on this system.
