### ISSUE TITLE
Change in base class does not trigger recompilation of derived classes and consumers

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#232]
Unless I'm mistaken this is supposed to be a supported scenario right?
I'm changing the access level of some base class properties/methods (from public/protected to private) and would expect any consumer/caller to get recompiled, but this is not happening.
What am I doing wrong and/or how can I debug the cause?

**Comment by gquerret** [comment]
Access modifier is currently not taken into account in the hash that triggers the recompile 😳
Will be fixed.

**Comment by gquerret** [comment]
Fixed, will be available in next pre-release

**Comment by gquerret** [comment]
That was included in 1.13.6 (reelased on Oct. 18th).
