### ISSUE TITLE
Outline of class different icons according to the access of the method

### ISSUE THREAD

**Issue by ppyck** [vscode-abl/vscode-abl#236]
When looking at the outline of a class, it would be usefull to see which methods are private, protected, public ...
now I have a puple box in front of each method. By giving the constructor(s) and destructor a different icon and each method an icon according to the access the outline would be clearer

<img width="289" alt="image" src="https://github.com/user-attachments/assets/23c17dd4-b0e7-4a5c-917b-b0fa0212d003">

**Comment by gquerret** [comment]
Those symbols are not yet available in the Language Server Protocol. I'll work on the OE implementation as soon as this is part of the specification. But no idea *when* that will be available, I have strictly no control over that.
