### ISSUE TITLE
Data Dictionary doesn't connect to DBs in profiles

### ISSUE THREAD

**Issue by RobinJPowell** [vscode-abl/vscode-abl#243]
When using profiles which define their own set of dbConnections, the Data Dictionary does not connect to these DBs when using the profile, it is always connected to the default set.

**Comment by gquerret** [comment]
Confirmed, will be fixed.

**Comment by gquerret** [comment]
Fixed in 1.15.0

**Comment by gquerret** [comment]
That will in fact be available 1.15.1
