### ISSUE TITLE
"Uncaught Errors" in Runtime Status view of extension

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#245]
This might be harmless, but reporting it anyway...

![image](https://github.com/user-attachments/assets/616d8e30-c546-4609-b6c3-8bccc62a1c08)

**Comment by gquerret** [comment]
Unfortunately couldn't reproduce, and I really don't see what could be the cause. Please reopen if you have any extra details that could lead to the source of the problem.
