### ISSUE TITLE
Migrate PDSOE project files

### ISSUE THREAD

**Issue by stefandrissen** [vscode-abl/vscode-abl#25]
My PDSOE environment is completely configured and purring.

I am unable to quickly start vs code since I then need to think about my configuration and reshuffle.

An initial migration that picks up .project and .dbconnection settings from a PDSOE project would really help.

**Comment by gquerret** [comment]
I could be possible to have a standalone application that would convert the PDSOE configuration files into openedge-project.json.

* `.propath` contains the default build directory, propath entries (with build output). It may be useful to have a command line switch to handle TTY or GUI information (and maybe Platfrom attribute)
* `.project` doesn't have any useful information
* `.dbconnection` only contains references, so a command line parameter should be there to point to the full XML file

**Comment by gquerret** [comment]
@cverbiest created a [migration script](https://github.com/cverbiest/pct-utils/blob/master/src/vscode/generate_riverside_vscodeconfig.p) some time ago. That can be used as a starting point for the VS Code config.
