### ISSUE TITLE
Highlighting while Ctrl is held is misleading

### ISSUE THREAD

**Issue by Mattwmaster58** [vscode-abl/vscode-abl#250]
This is a very minor issue which I hope is an easy fix.

I use Ctrl+Click for goto definition in VS Code. When hovering over an include path, the highlighting behavior is not perfect. When my mouse is above each blue bar in the image below, only that token is highlighted: (although the action still works perfectly)
![image](https://github.com/user-attachments/assets/b4f36091-bedb-4ccf-92d1-278f1650809c)
I think the entire path being highlighted for any part of the path being hovered is more accurate (note that the braces are highlighted even, this does not occur under any conditions I've found currently with this extension):
![image](https://github.com/user-attachments/assets/2d14fd4a-18a6-47bb-bec8-16bbf6450700)

**Comment by gquerret** [comment]
Yes, the source range is not passed by the language server, and VS Code use `/` as a separator. Will try to improve that.

**Comment by gquerret** [comment]
Fixed in develop branch. Will be included in 1.17.x pre-release.
