### ISSUE TITLE
.cls files are not run properly

### ISSUE THREAD

**Issue by StaelensJarne** [vscode-abl/vscode-abl#254]
I have a configuration that is generated by the "generate_riverside_vscodeconfig" p-file.
```
{
  "name": "application",
  "version": "1.0",
  "oeversion": "12.8",
  "graphicalMode": true,
  "charset": "ISO8859-1",
  "extraParameters": "-basekey ini -debugalert -inp 16000 -tok 4000 -rereadnolock -s 200 -mmax 65534",
  "workingDirectory": "C:\/Users\/jarne\/Documents\/MyNewWorkspace\/DochyERP",
  "numThreads": 1,
  "buildPath": [
    {
      "type": "source",
      "path": "src",
      "build": "rcode"
    },
    {
      "type": "propath",
      "path": "."
    },
    {
      "type": "propath",
      "path": "C:\/Progress\/OpenEdge\/gui"
    },
    {
      "type": "propath",
      "path": "C:\/Progress\/OpenEdge"
    },
    {
      "type": "propath",
      "path": "C:\/Progress\/OpenEdge\/bin"
    }
  ],
  "dbConnections": [
    {
      "name": "Dochy",
      "connect": "-db C:\/DB\/DochyDB\/dochy.db -H localhost -S 50001",
      "schemaFile": "C:\/Users\/jarne\/Documents\/MyNewWorkspace\/DochyERP\/db\/dochy.df",
      "aliases": []
    }
  ]
}
```

My configuration is valid but when I try to run any .cls file in my project it is not started correctly.
When I try to compile the file in vscode, it compiles succesfully.

If I look in the output of my log file in the .builder folder (clientlog0.log).
It is trying to connect to the backend on port 58123. But I never configured port 58123 in my config file.

And if I open the rungui.log, it shows me that the file is running, but without futher output.
I see a progress window open, but not the form itself.
I seems that it is triyng to run the file, but it cannot find the correct GUI components, to show the form.

How can I troubleshoot this problem?

**Comment by PeterJudgeZA** [comment]
The ABL can't run classes natively - it needs a .P somewhere to instantiate them. PDSOE has some specialed ones that will launch a form. 

I'm not sure whether there are such .P's in the VSCode extension.

**Comment by StaelensJarne** [comment]
In the Progress Developer Studio, I can run classes natively. I have many run configurations in developer studio that direcly start a .cls file. Do you mean that the VSCode extention does not support classes (.cls files) ?

But I do can sucessfully compile .cls files with the extention.

So than I need to write a p-file to start a .cls file in vs-code ?

**Comment by gquerret** [comment]
I didn't even know it was possible to execute a class from the procedure editor or from developer studio.
So no, it's not possible to do that in VS Code, you can only execute procedures.

**Comment by StaelensJarne** [comment]
So, now I am confused.
 
Why can you set "graphicalMode": true in the project configuration?
In the README it is documented that you can set this.

A p-file should be run with _progress. But in visual studio code I also see the command:
ABL: Run with prowin

**Comment by gquerret** [comment]
* `graphicalMode` attribute controls the type of AVM that compiles in the background (`_progres` when false, `prowin` when true).
* When there's no UI, compiled with `prowin` can be executed in `_progres`. And a `.p` (without UI) compiled with `_progres` can also be executed in `prowin`
