### ISSUE TITLE
Data Dictionary doesn't acknowledge change in db connections

### ISSUE THREAD

**Issue by ntreeby** [vscode-abl/vscode-abl#30]
Say I configure my project to connect to 2 databases: db1 and db2.

I put these connections in the openedge-project.json config file, and start the ABL Language Server.  The ABL background processes that start are connected to db1 and db2.  If I open the Data Dictionary, I see db1 and db2.

Now, say I change the connections so that instead of connecting to db2, I connect to db3; and restart the ABL Language Server.  The ABL background processes are now connected to db1 and db3.  But, when I open the Data Dictionary, I still see db1 and db2.

The Data Dictionary uses a temp JSON configuration file stored (in Windows) in %USERPROFILE%/AppData/Local/temp, it seems that when the database connections are changed in openedge-project.json and the ABL Language Server is restarted, this temp JSON file is not updated / deleted and is re-used when the Data Dictionary is launched.

I assume a workaround would be to delete this temp file before launching the dictionary.

**Comment by gquerret** [comment]
It looks like the VSCode project configuration is not refreshed on-the-fly. Will have a look.

**Comment by gquerret** [comment]
The file watcher was on the old configuration (.openedge.json) instead of the new openedge-project.json.
Will be part of next release.
