### ISSUE TITLE
BUG: ABL Language Server throws Syntax Error

### ISSUE THREAD

**Issue by Hoempi** [vscode-abl/vscode-abl#31]
Whenever the Language Server starts I get the following error:

> [2022-10-14T15:47:47.227+0200] [ERROR] Syntax error <unknown>:467723:9 mismatched input '1252' expecting UNQUOTED_STRING
> [2022-10-14T15:47:48.452+0200] [ERROR] Syntax error <unknown>:47817:9 mismatched input '1252' expecting UNQUOTED_STRING
> [2022-10-14T15:47:48.490+0200] [ERROR] Syntax error <unknown>:1370:9 mismatched input '1252' expecting UNQUOTED_STRING

I got three databases connected. If I only connect one, I only get the error once. My project config looks like this:
```
{
    "name": "Test-Project",
    "version": "1.0",
    "oeversion": "12.2",
    "graphicalMode": true,
    "charset": "cp1252",
    "extraParameters": "-pf D:/temp/main.pf",
    "buildPath": [
      { "type": "propath", "path": "src" }
    ],    
    "dbConnections": [
      {
        "name": "main",
        "connect": "-db db1 -H localhost -S 35000 -N tcp -U %user% -P %pass%",
        "dumpFile": "d:\\temp\\df\\db1.df",
        "aliases": [ ]
      },
      {
        "name": "add1",
        "connect": "-db db2 -H localhost -S 35002 -N tcp -U %user% -P %pass%",
        "dumpFile": "d:\\temp\\df\\db2.df",
        "aliases": [ ]
      },
      {
        "name": "add2",
        "connect": "-db db3 -H localhost -S 35003 -N tcp",
        "dumpFile": "d:\\temp\\df\\db3.df",
        "aliases": [ ]
      }            
    ],
    "numThreads": 1,
    "procedures": [ ],
    "profiles": [  ]
  }
```

**Comment by gquerret** [comment]
This message is just a warning (even if it says `ERROR`), so you can safely ignore it. The dependency which produces this message has been fixed, so you won't see the message in the next version the plugin.
