### ISSUE TITLE
Inconsistent file name casing

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#34]
We're trying to get used to lower case coding (ugly I know).

But when using VS Code, the intellitype is proposing uppercase keywords - but when typing the keywords are kept in lowercase.

CAn the intellitype please also propose lowercase keywords - or add an option for that? 

![2022-10-20_09h00_33](https://user-images.githubusercontent.com/13220627/196881533-29cba45e-1536-49ee-9f1d-1154372f8756.gif)

**Comment by gquerret** [comment]
Did you try `abl.completion.upperCase` ?

![image](https://user-images.githubusercontent.com/6498723/197942943-35e5e27b-5cff-4208-961e-bdd5cb47d497.png)

**Comment by mikefechner** [comment]
This is a workspace which is configured to lower-case:

![image](https://user-images.githubusercontent.com/13220627/198199753-3b575714-f26f-4ace-947a-258fa135d7f3.png)

I'm not getting upper-case keywords while I type. 

I am getting upper-case keywords picking getting them from the list of proposals:

https://user-images.githubusercontent.com/13220627/198200001-674e5ef5-b3fc-461e-82ec-1f902ba950b1.mp4

**Comment by gquerret** [comment]
Can you also try setting `editor.wordBasedSuggestions` to false in your settings.json file ? This prevents VSCode from injecting "words" found in the current file in the autocompletion.

**Comment by mikefechner** [comment]
That seems to work! Merci!
