### ISSUE TITLE
@SkipSonar. is not recognized

### ISSUE THREAD

**Issue by cverbiest** [vscode-abl/vscode-abl#39]
Following code is flagged by sonar. 
I used Mike's routine to generated cabl.json, but that probably does not contain the global sonar settings

```
@SkipSonar. // shared variable required to get Verbose flag of PCTRun
  do:
  define new global shared variable pctVerbose as logical no-undo initial no.
  end.
```

```
[{
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": "rssw-oe-main:EmptyBlock",
	"severity": 2,
	"message": "Code block doesn't have any statement and no comment to explain why",
}]
```

**Comment by gquerret** [comment]
Mike's procedure is a temporary workaround, as the aim is to have the same integration as in Developer Studio (bind project to remote server, and fetch the quality profile). However, this is not as easy as in PDSOE, as the entire SonarLint stack has to be imported in the language server.
Feature is very high on the wish list though.

**Comment by gquerret** [comment]
Additional property will be available in VSCode config, and passed to SonarLint during the analysis

**Comment by gquerret** [comment]
Property added in 1.5.6
