### ISSUE TITLE
Using the extension on Ubuntu 20.04

### ISSUE THREAD

**Issue by lievencardoen** [vscode-abl/vscode-abl#40]
Hi Gilles,

I'm trying to use this extension in vscode on Ubuntu 20.04.

Seems to be working ;-).

Have others tried this?

Is there a way to run ABL Unit Test Classes?

Thx, Lieven

**Comment by gquerret** [comment]
I know a few people have tried (successfully) using the VSCode plugin on Linux. As long as the Linux platform is supported by Progress, it will be possible to use it with VSCode.

Regarding ABL Unit tests, there's no specific way to execute the unit tests. You may try executing them from Ant (there's a vscode plugin for that), or directly with VSCode tasks.

**Comment by lievencardoen** [comment]
What I can't seem to get working is a full build. I'm able to run a procedure (p file) but I'm not able to compile it. 

This is my openedge-project.json file:

```
{
  "name": "MyProject",
  "version": "1.0",   
  "oeversion": "12.2", 
  "graphicalMode": false, 
  "charset": "utf-8", 
  "extraParameters": "",
  "buildPath": [
    { "type": "source", "path": "src" }
  ],
  "buildDirectory": "build", 
  "dbConnections": [ 
    /*{
      "name": "sp2k", 
      "connect": "-db db/sp2k -RO", 
      "dumpFile": "dump/sp2k.df",  
      "aliases": [ "foo", "bar"] 
    }*/
  ],
  "numThreads": 1,
  "procedures": [ 
    { "name": "foo/bar.p", "mode": "once"  }
  ],
  "profiles": [  ]
}
```

I have one test.p in src folder.

Running ABL: Rebuild project doesn't do anything... Is there a way to debug this? A log file showing what's happening in the background?

**Comment by lievencardoen** [comment]
Ahhh, it's working now. Restarted vscode and now I think it has picked up the new openedge-project.json (had changed it).

Man, thx for this. I can now work on linux with an ide.
