### ISSUE TITLE
Enhancement Outline filter locally defined

### ISSUE THREAD

**Issue by cverbiest** [vscode-abl/vscode-abl#41]
Our procedures contain a lot of functions and procedures that are defined in include files.
(adm includes, external function definitions for persistent procedure libaries, ...)

It would be very nice to be able to show only the locally declared function/procedures.

Currently the outline is not really useful for the adm based UI.

**Of all entries in the screenshot only one is locally defined. .**

![image](https://user-images.githubusercontent.com/1312691/201932028-b6391bf8-7f8e-448c-8e3f-4fe919ba7154.png)

Personally, I'm not interested in variable definitions in the outline.
A toggle to hide those would be helpful as well.

**Comment by gquerret** [comment]
I agree that filtering would be useful. There are options for hiding variables in the outline: https://code.visualstudio.com/updates/v1_40#_type-filters-for-outline-and-breadcrumbs
Can you try that ?

**Comment by gquerret** [comment]
Controlled by `abl.outline.showIncludeFiles` and `abl.outline.showContentInIncludeFiles`
