### ISSUE TITLE
New class file skeleton

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#47]
When creating a new class file in a VS Code project, please implement a class skeleton:

- block-level on error undo, throw
- using for it's own package (using Test.MyPackage.* from propath.)
- class statement (class Test.MyPackage.MyClass)

As the community probably won't agree on a template for a new class file (e.g. default using's), a dynamic template structure (similar to JET in Eclipse) would be useful.

Alternatively, let us implement an .p file that you pass:

- absolute name of new file
- relative name of the new file (relative to project root)

and let us populate the file contents.

**Comment by gquerret** [comment]
Code snippets can be used in this case: https://stackoverflow.com/a/73043147

**Comment by mikefechner** [comment]
That seems to only allow for static snippets as templates, e.g. no way to include the class name and folder name translated into a package into the new file.

Looks like we'll have to add a simple class template in our own scaffolding framework then.

**Comment by mikefechner** [comment]
Provides the path as a variable – but for package I need it with periods – not slash or backslash.

**Comment by gquerret** [comment]
Could this be useful : https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variable-transforms ?

**Comment by gquerret** [comment]
Looks like it's possible to transform variables: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_transform-examples

**Comment by PeterJudgeZA** [comment]
This doesn't provide everything, alas. It lokos like you can do a single transform: a "new class" would need 2 - 1 for the path names, and 1 to remove the `.cls` extension.


The snippet below
````json
	"new-class" : {
		"scope": "abl",
		"description": "New class body",
		"prefix": "",
		"body": [
			"block-level on error undo, throw.",
			"",
			"class ${RELATIVE_FILEPATH/(.*)\\..+$/$1/}",
			"class ${RELATIVE_FILEPATH/[\\\\]/./g}",		
			"end class."
		]
	}

````
produces
````
block-level on error undo, throw.

class temp\package\newclass
class temp.package.newclass.cls
end class.
````

Combining the body transforms into

````json
"class $${RELATIVE_FILEPATH/(.*)\\..+$/$1/}/[\\\\]/./g}",
````
results in 
````
class $temp\package\newclass/[\]/./g}
````

**Comment by gquerret** [comment]
Didn't give it a try, but this SO post shows that it's possible to apply multiple transformations: https://stackoverflow.com/questions/58740859/vs-code-snippet-with-multiple-transforms
