### ISSUE TITLE
AND keyword not coloured correctly when on IF line

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#50]
This code
````
IF THIS-OBJECT:DefaultBufferNames > "":U AND
NUM-ENTRIES(THIS-OBJECT:DefaultBufferNames) >= iTable
THEN
````

is mostly highlighted corectly, but the trailing `AND` is left as black (or otherwise not highlighted as a keyword).

![grafik](https://user-images.githubusercontent.com/8291561/211404276-408c87b8-6d2a-4354-9b9d-b4cb10591ea3.png)

Similarly, the NOT below has the same issue
````
IF NOT VALID-HANDLE (phDataset) OR phDataset:TYPE <> "DATASET":U THEN
````

Extension version 1.4.4

**Comment by gquerret** [comment]
None of the operators were highlighted. Fixed in development, will be included in next release.
