### ISSUE TITLE
Debugger breakpoints don't seem to work; Potential debugger improvement

### ISSUE THREAD

**Issue by kenherring-rkt** [vscode-abl/vscode-abl#53]
## Potential Debugger Issue

First, what seems to be an issue:  when using the debugger with the suggested configuration from the README it seems that breakpoints are no longer functional.  I can start the debugger, it stops on the first line of DynRun.p, and then stops again on the first line of my program.  However, it will not stop again on any breakpoints that I set.  I could put together a sample project if necessary, though really it won't be anything special.

Stepping through code and using the `debugger:set-break()` method seem to work fine.

On the same topic, watch points don't appear to work but I assume it's related to breakpoints being non-functional.

I do see messages about the breakpoints being set in the logs:

```
[2023-01-15T16:22:28.054-0500] [INFO] eu.rssw.openedge.dap.a - Set breakpoints request for c:\git\amp-metrics\src\oe\test.p
[2023-01-15T16:22:28.055-0500] [INFO] eu.rssw.openedge.dap.a - Add message to queue: break B;1;E;test.p;2; ;B;2;E;test.p;3; ;B;3;E;test.p;4; ;B;4;E;test.p;6; ;B;5;E;test.p;7; ;B;6;E;test.p;10; ;
```

proversion: 12.2.0.0.1170

Also, is the code for `abl-dap.jar` public at all?  I setup this repo to try and debug this myself, but it appears that it might be happening within this code which I can't find.

## Potential debugger improvement

Would it be possible to have the process run in a terminal (when tty mode only most likely) and have output go to a terminal right in vscode?  Multiple windows is quite annoying to work with as someone who doesn't want to leave VSCode.

I suspect there may be issues with the `Use port 9999 for the Debugger to connect to. (11725)` message and timing of attaching to the process that make this difficult.

Again, I tried to test this idea out locally with this project, but without the `abl-dap.jar` code it doesn't seem likely I could make it work.

## Summary of questions

* Is there an issue with the debugger, or am I doing something wrong?
* Is the `abl-dap.jar` code available to debug locally?
* Would it be possible to run a tty debug session directly in vscode?

**Comment by gquerret** [comment]
I'll have a look at the debugger breakpoints, but sure there's room for improvement. They are supposed to work correctly, but I'll double check. Did you try on Linux or on Windows ?

> Would it be possible to have the process run in a terminal (when tty mode only most likely) and have output go to a terminal right in vscode? Multiple windows is quite annoying to work with as someone who doesn't want to leave VSCode.

It was much easier to start the application in an external session rather than in terminal. On top of that, the tests that were done on different TTY applications didn't show very good results in the VSCode terminal. Not sure who is at fault between VSCode and Progress.

> Is the abl-dap.jar code available to debug locally?

No, this source code is not public.

**Comment by kenherring-rkt** [comment]
> Did you try on Linux or on Windows ?

Windows.  If you have trouble recreating it let me know and I'll put together a bare minimum example to share.

> It was much easier to start the application in an external session rather than in terminal.

I figured as much.  The difference in terminal preferences makes this tricky.  I prefer git bash which seems to work OK for us.  We might be primarily using WSL for other reasons soon, which could change this.  Thanks for the info, and if you get the desire to change it I'm sure we could test it out 😎

> No, this source code is not public.

Cool, thanks.

**Comment by kenherring-rkt** [comment]
Closing for now.  I think we might be able to use a `preLaunchTask` to accomplish this workflow and will share when I get around to configuring it.

**Comment by gquerret** [comment]
Note that breakpoints have been improved, an issue was spotted during our tests. That will be part of next release.
