### ISSUE TITLE
ABL:Run with prowin customize

### ISSUE THREAD

**Issue by lievencardoen** [vscode-abl/vscode-abl#55]
Hi, is there a way to add parameters to the run?

Is there also a way to configure the call to prowin?

Something like 

- prowin | tee 
- prowin -param "blah"
- ...

Thx, Lieven

**Comment by gquerret** [comment]
The `extraParameters` attribute from `openedge-project.json` are always appended, but that's not really flexible.
Otherwise, you use tasks in VSCode to customize the command line that you want to execute.
