### ISSUE TITLE
maxNumThreads as user settings

### ISSUE THREAD

**Issue by clement-brodu** [vscode-abl/vscode-abl#58]
Allow each user to set a `maxNumThreads` to limit the number of thread per project.

Ex: the versionned file "openedge-project.json" contains `"numThreads": 10` but I want to limit to 2 threads without impacting my colleagues

**Comment by gquerret** [comment]
> Allow each user to set a maxNumThreads to limit the number of thread per project.

Interesting idea. Note that settings can also be per workspace ( https://code.visualstudio.com/docs/getstarted/settings ).

**Comment by gquerret** [comment]
Merged in main
