### ISSUE TITLE
Code completion suggestions not suggesting buffers

### ISSUE THREAD

**Issue by danielbecroft** [vscode-abl/vscode-abl#61]
### Problem 1: buffers not used as suggestions
When a buffer has been defined, the auto-complete code suggestions are not suggesting this option:

Example (using the `sports2000` database.
```
define buffer bCustomer for Customer.

for each _
```

When the cursor is at the `_` position, I get every table available in the database, but not the `bCustomer` buffer. Even if I type `bCu`, then nothing appears as suggestions.

### Problem 2: fields not being suggested

Again, using the `sports2000` database:

```
for each Customer
    where Customer.
```

After the `.`, when hitting Ctrl+Space for suggestions, only table names are populated. No fields are shown.

I am using 11.7.15 64-bit, on Windows. VS Code 1.76.1.

**Comment by gquerret** [comment]
Regression in last version. Will be fixed in a couple days.
