### ISSUE TITLE
Automatic indent in block works off last line not start

### ISSUE THREAD

**Issue by danielbecroft** [vscode-abl/vscode-abl#65]
I'm observing some behaviour that I think is incorrect

When typing the following block:

```
define variable vIndex as integer no-undo.

do vIndex = 1 to 2:
```

Hitting ENTER after the colon puts the cursor indented at (a):

```
define variable vIndex as integer no-undo.

do vIndex = 1 to 2:
    |
    ^
```
Then typing `end.` puts it back in line with the `DO`, which is correct (IMO).

```
define variable vIndex as integer no-undo.

do vIndex = 1 to 2:

end. 
```
  
But, for a `FOR EACH` block, or where the `DO` block includes multiple lines:

```
TRANSACTION-BLOCK:
do on error UNDO TRANSACTION-BLOCK,
    leave TRANSACTION-BLOCK:
        |
       ^a
    |
    ^b
```

The cursor is indented one level from the `LEAVE` line (a), when it should be the `DO` line (b). 

If I left the cursor where it was, the block would look like:

```
TRANSACTION-BLOCK:
do on error UNDO TRANSACTION-BLOCK,
    leave TRANSACTION-BLOCK:

        // do the thing
        
    end. 
```

(It's hard to explain the behaviour here, but hopefully that is clear).

**Comment by gquerret** [comment]
This issue is painful, though it has been present for years. Time to get rid of it ! 🚀
