### ISSUE TITLE
Code completion/outline not working

### ISSUE THREAD

**Issue by xGerTowelie** [vscode-abl/vscode-abl#67]
Code completion is not working for me. In the following screenshot I edit a class which is added to the propath:

![image](https://user-images.githubusercontent.com/128218084/228320209-5e9d0b91-959a-4158-8515-38a0da99dee8.png)

![image](https://user-images.githubusercontent.com/128218084/228320520-18cfc1a3-873a-4f65-8c86-82c3ccfc7bc8.png)

The debug listing of the language server just shows this single line, whenever I press CTRL + SPACE:

![image](https://user-images.githubusercontent.com/128218084/228320823-7ea6ad55-81da-4cee-9acd-f36839832f40.png)

Compiler is working:

![image](https://user-images.githubusercontent.com/128218084/228321167-fd949ac9-ca41-4b08-813d-b3d1ada1aa25.png)

Tables aren't provided in the autocomplete as well. When I use the command "ABL: open DataDictionary" I obviously see my tables:

![image](https://user-images.githubusercontent.com/128218084/228321865-30c8a6d0-e90e-488c-9216-bef93380fade.png)

Calling the "ABL: Read Dictionary Structure" I get this error:

![image](https://user-images.githubusercontent.com/128218084/228322713-99780f13-c125-4589-abba-714e10b3a4cb.png)

In the openedge-project.json I tried referencing the DF with absolute and relative paths. Both did not work for me... But I think the file get found correctly, because if I declare a wrong DF the language server crashes:

![image](https://user-images.githubusercontent.com/128218084/228323484-a683e97b-f03e-4981-8cb4-f49114c406fa.png)

Are there any suggestion on how to get code completion to work?

**Comment by gquerret** [comment]
Source directories are resolved against the root directory of the project (where openedge-project.json resides). Can you try using relative paths instead ?
See this file for a sample config:
https://github.com/Riverside-Software/sonaroe-test-project/blob/main/openedge-project.json
