### ISSUE TITLE
ABL LSP continues to run after close of vscode

### ISSUE THREAD

**Issue by ChadThomsonPSC** [vscode-abl/vscode-abl#69]
When opening vscode (with the OpenEdge ABL plugin installed, of course), and opening folder or workspace with an `openedge-project.json` file or editing an individual ABL file, the expected ABL Language Server (ABL LSP) Java process (abl-lsp) is started.  After closing vscode, the ABL LSP process remains running, creating unmanaged processes and causing undesirable side-effects.

The situation is reproducable when running vscode locally or through remote SSH vscode connection.

In the later scenario, as this process is repeated (open vscode, edit ABL file, observe ABL LSP startup, close/stop vscode) the number of ABL LSP processes increases -- including when the remote vscode server process stopping due to timeout or termination. 

The ABL LSP should provide one or more configuration and control options for
- stopping the ABL LSP (per-project, per-workspace, entirely) manually
- stopping after the editor (vscode, code server) is closed/quit/completely stopped

Processes can be enumerated using the Java `jps` command:
```SHELL
$ jps -l 
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> jdk.jcmd/sun.tools.jps.Jps
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
```
In case there are a number of Java processes on the target system, add a `grep` for `abl-lsp` as:
```SHELL
$ jps -l | grep "abl-lsp"
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
<pid> <ref-folder>/.vscode-server/extensions/riversidesoftware.openedge-abl-lsp-1.4.8/resources/abl-lsp.jar
```

Tested with the following:
- VSCode: 1.76.0
- OE ABL Plugin: v1.4.8
  - Last released: 3/30/2023, 04:01:01
  - Last updated: 3/31/2023, 12:14:39
- Local environment: 
  - MacOS 13.3
  - Java version: openjdk version "19.0.2" 2023-01-17
  - OpenEdge version: none, plugin provides simple source coloring 
- Remote environment:
  - Linux: Ubuntu 20.04.6 LTS
  - Java: openjdk version "11.0.18" 2023-01-17
  - OE Version: OpenEdge Release 12.2.8 as of Fri Mar 25 18:13:26 EDT 2022

**Comment by gquerret** [comment]
This behavior is confirmed, that will be fixed.

**Comment by gquerret** [comment]
Project shutdown should now be handled correctly (if the client correctly sends the stop message). Fix included in 1.4.9. Please reopen if you still see issues.

**Comment by ChadThomsonPSC** [comment]
I have built the main branch, which contains the update with the deativate hook. This should be representative of v1.4.9.

Following installation of the extension into a vscode remote workspace, and verification of the correct extension version, the language server process remains upon close of the workspace, vscode editor, and even killing of the vscode server (via vscode tooling and OS kill $PID).

> Project shutdown should now be handled correctly (if the client correctly sends the stop message). Fix included in 1.4.9. Please reopen if you still see issues.

How does the client send a "stop message"? There are options to restart the language server, but I do not see a "stop" command.

**Comment by gquerret** [comment]
@ChadThomsonPSC 1.4.9 was released on Friday. Did you try this version?

**Comment by ChadThomsonPSC** [comment]
I'm running v1.4.12 and the update seems to be working as expected.  

There are no more LS left-overs after closing the workspace (remote and local) or disconnecting from a remote.  

Fixed!
