### ISSUE TITLE
Delayed extension startup

### ISSUE THREAD

**Issue by kenherring-rkt** [vscode-abl/vscode-abl#70]
Would it be possible to have a setting to delay the startup of the extension by some amount of time?  I'm not sure I love this solution for the problem I'm trying to solve, but it would be helpful.

**openedge-project.json**
```jsonc
  "delayStart":"10" //seconds
```

## Problem

When we start VSCode we create schema DBs for compiling that are used by the extension.  When schema changes we may want to delete these DBs and recreate them.  This is all done via a task in `tasks.json`.

If the DBs already exist, or don't exist, the extension starts and tries to begin compiling nearly immediately.  At that point the DBs are in use and cannot be removed (and then recreated).  Delaying startup would give the script time to do it's work, and then the extension would start and connect to the new DBs.

It's not an elegant solution, so totally understand if we want to skip this idea.  I could see it being useful for docker container startups too though.

**Comment by gquerret** [comment]
You'll be able to implement that as part of #100
