### ISSUE TITLE
"Indentation of statement is not correct" - reporting erroneously

### ISSUE THREAD

**Issue by kenherring-rkt** [vscode-abl/vscode-abl#74]
Hey @gquerret!  Been seeing a bunch of this warning with the newest version of the plugin.  Maybe this is related to [sonar-openedge](https://github.com/Riverside-Software/sonar-openedge) instead though?

![image](https://user-images.githubusercontent.com/87667618/235163427-d34c3591-02ef-4418-857a-99b644bcaac7.png)

Here's a simple class to recreate it:

```abl
block-level on error undo, throw.

class IndentWarning :

  constructor protected IndentWarning () :
    //nothing here
  end constructor.

  method private logical method1 () :
    if false then
    do:
      method2().
      return no. //Indentation of statment is not correct
    end.

    if true then
    do:
      return no.
    end.

    if true then
      return yes.

    return yes.
  end method.

  method private void method2 () :
    //nothing here
  end method.

end class.
```

**Comment by gquerret** [comment]
Thanks @kenherring-rkt for the report ! OE Plugin 2.21.0 is about to be released, and was delayed because of this issue (and a few other related ones). VSCode plugin although bundled this specific version. A new version of the plugin will be released soon (probably end of day).

**Comment by kenherring-rkt** [comment]
Very cool, thanks!
