### ISSUE TITLE
Include file with multi-line arguments causes parser and syntax highlighting issue

### ISSUE THREAD

**Issue by tonhuisman** [vscode-abl/vscode-abl#77]
When having this include line in my source:
```
    {rec/zetin.ooi &where="zetin.act  
                       AND CAN-FIND(FIRST ztihu WHERE ztihu.zetin_iden = zetin.zetin_iden)"}
```
The rest of the file is missing code-completion, because the parser doesn't handle this, and also it's 'browned-out' by the syntax highlighter, because of an un-terminated string.
Removing the line-break within the passed string does solve it, but as the ABL compiler and OpenEdge Editor do allow this kind of syntax, it would be nice to have the plugin handle this properly also.

As we have quite a lot of sources using this type of includes, we'd have to change quite a lot of code, and make it less comprehensible, to effectively use the plugin.

**Comment by gquerret** [comment]
While syntax highlight is broken, code completion is not broken (at least in my tests) as this is handled differently.

Syntax highlight is currently done by the TextMate grammar, based on regexp. I'll have a look at that case, and add a fix in future versions if that doesn't break too many things.

**Comment by gquerret** [comment]
The fix will wait for the semantic highlighting to be implemented in the language server (see [this thread](https://github.com/microsoft/vscode-textmate/issues/41) on why it's impossible to implement that with TextMate grammars). Note that the language server already has all the information to provide the semantic highlight information, so it's *just* 😄  a matter of implementing the entrypoint.

**Comment by gquerret** [comment]
Note that the prototype of the semantic highlighting is successful. That won't come in the very near future due to other priorities, but at least there's some progress !

**Comment by ScarTheSilent** [comment]
What's the state of semantic highlighting. I've come across a similar issue in our source code. For instance if I have this code:

```
DELETE PROCEDURE test.

RUN kill-prog("test1.p").
RUN kill-prog("test2.p").
```

The RUN lines are treated like they're within quotation marks, but if I put a space after "test" and before the "." on the first line then it fixes further lines. I'm making the assumption that that's due to the same issue with TextMate.

**Comment by gquerret** [comment]
Semantic highlighting is included in the prerelease stream of the extension (you have to switch to prerelease for this vscode extension). Note that this might not be very stable...

Then it's disabled by default, so add this section in your `settings.json`:
```
    "[abl]": {
        "editor.semanticHighlighting.enabled": true
    }
```

Colors can be a bit weird, but this is controlled by the theme. It's also a bit slower on large files (shouldn't be noticable on small files).
Semantic highlight is work in progress, no need to report issues regarding the (lack of) quality of the semantic tokens.

**Comment by gquerret** [comment]
Closing issue as this is fixed in semantic highlighting (and will never be fixed in the TextMate grammar).

**Comment by PeterJudgeZA** [comment]
@tonhuisman This may be improved in the latest grammars. There are certain things that cannot be done without semantic highlighting, as @gquerret  says, but there are some changes made to the grammar that improve the highlighting in the cases mentioned in this issue.

**Comment by tonhuisman** [comment]
@gquerret I hadn't checked for some time, but current released extension solves the highlighting issue, as described in my original comment. Thank you for fixing that 👍
