### ISSUE TITLE
ALIAS - error in ABL Langage server log and sonarlint

### ISSUE THREAD

**Issue by clement-brodu** [vscode-abl/vscode-abl#85]
Here is my case : 

- I have a standard database with a logical name "Bob". It's always the same logical name.
- The physical name may change, so the *.df and *.db have a different name (for exemple : "Bob3" for the 3rd version of Bob)

It's defined like that :

```json
    {
        "name": "Bob",
        "connect": "-db Resources/Undeployed/Databases/db/Bob3 -RO -ld Bob",
        "dumpFile": "Resources/Undeployed/Databases/df/Bob3.df",
        "aliases": ["BobFriend"]
      },
```

Here is the output of the langage server 
```
[2023-07-24T18:02:46.058+0200] [ERROR] Creating alias BobFriend for unknown database Bob
```

If I use the alias, my program compile.

```abl
DEFINE BUFFER toto FOR BobFriend.customer.
```

But there is a proparse error : 

```
[2023-07-24T18:12:08.206+0200] [ERROR] Proparse error in 'demo.p' at position d:\Openedge\workspace-oe11\demo\Src\demo.p:1:24
[2023-07-24T18:12:08.206+0200] [INFO] Compilation successful: demo.p
```

**Comment by gquerret** [comment]
There's an internal ticket about this problem. That will be fixed in the next release (in August).

**Comment by clement-brodu** [comment]
Thanks 👍 

Other question : would it be possible to automatically add the `-ld` depending with the name ?

**Comment by gquerret** [comment]
Done

**Comment by gquerret** [comment]
Note: the -ld is not added, you have to include it in the connection string. Adding -ld would break dataserver connection strings for example.
