### ISSUE TITLE
Code completion for data types suggested classes, not primitives

### ISSUE THREAD

**Issue by danielbecroft** [vscode-abl/vscode-abl#87]
Running v1.4.12, with 11.7 64-bit.

The code completion is acting strange when suggesting data types. If I have the following:

```
define variable vI as int
```

The suggestion list for the data type includes `IntegerArrayValueWriter`, `IntegerValueWriter`, and some others, but `integer` or `int64` is not in the list at all as an option. This isn't too bad when declaring variables, as I can write out the full name, then space and continue the declaration (add `NO-UNDO`, `INITIAL` etc as required).

The annoyance is for temp-tables, as the data type is the last thing we usually define, and hitting `Enter` is then seen as accepting the code-completion suggestion of `IntegerArrayValueWriter`, which then has to be reverted.

It's even stranger, in that if the line doesn't compile (for example, I have a typo in `define`, it suggests both `integer` and `INTEGER` as options).

```
deifine variable vI as int
^^^^^^
```

Here, `integer` and `INTEGER` are suggested, the classes aren't.

**Comment by gquerret** [comment]
I'll close for now ; not because it's wrong, but because a new version will be released this week with many changes in the code completion engine. Your issue is fixed in this version, but I'll let you reopen if you still see problems, and would like to suggest enhancements.
