### ISSUE TITLE
CTRL-Click on class name opens include file with same name

### ISSUE THREAD

**Issue by mikefechner** [vscode-abl/vscode-abl#91]
This is our pattern for pseudo generic classes in the ABL. We have a base class
```
Consultingwerk.Framework.Base.AblPrimitiveDictionary.cls 
```
with core functionality and an include file 
```
Consultingwerk\Framework\Base\AblPrimitiveDictionary.i
```
that exposes the "generic" methods, with the method return type or parameter type passed as an include file argument. 

When I CTRL-Click on the `INHERITS AblPrimitiveDictionary` in one of the implementing classes, the include file is opened - but the class file would be expected.

https://github.com/vscode-abl/vscode-abl/assets/13220627/c363845a-fc32-4381-af57-84d80e73da8a

**Comment by gquerret** [comment]
Very interesting behavior 😲 
Will be fixed

**Comment by gquerret** [comment]
Fixed
