### ISSUE TITLE
Exclude  *.w not working + enhancement request

### ISSUE THREAD

**Issue by cverbiest** [vscode-abl/vscode-abl#94]
I'm having trouble configuring excludes in the buildPath. Running vscode over shh on linux.

## Issue
```
    {
      "type": "source",
      "path": "git/ccesmarttools/CceSmartTools/src", 
      "excludes": "*.w,*Control.cls,*Form.cls,be/cce/ccetools/SchemaInfoUI/**,be/cce/ccetools/winkit/**,be/cce/ccetools/base/**,cceinc/**,be/cce/ccetools/document/**,be/cce/ccetools/infragistics/**,be/cce/ccetools/ui/**,be/cce/ccetools/dotnet/**,be/cce/ccetools/mq/**"
    },
```

With the above entry, I still get compile errors reported on 

* .w file' s
* git/ccesmarttools/CceSmartTools/src/be/cce/ccetools/infragistics/StyleLibraryHelper.cls
* git/ccesmarttools/CceSmartTools/src/be/cce/dotnet/Menu/ISubDivisionDataService.cls
* ...

Currently, I have 10K+ problems.
If I add `"includes":"*.p,*.cls",` to the path entry, I get 0 problems, so I'm probably doing it all wrong.

**How should I specify include/exclude ?**

## Related request

Our current exclude mechanism contains a lot of options. It dates back to when we used our own application compiler.
A single src can contain server-only and client-only code. It can also contain optional code that e.g. requires an optional database.
 
For PCT build I generate an exclude file using a progress procedure.
This exclude file is based on

* exclude a source if a required db is not available
* exclude if a certain application module is not active
* exclude on windows, on tty, or completely

**Could such a generated exclude file be taken into account by the exclude mechanism ?**

**Comment by gquerret** [comment]
There's no additional log output to debug include / exclude issues, but your excludes pattern looks good. Could you add entries one by one ?
The default include pattern is: `**/*.p,**/*.cls,**/*.w,**/*.i` 

Regarding your extra request: do you use the excludesfile attribute of [Ant fileset](https://ant.apache.org/manual/Types/fileset.html) ?

**Comment by cverbiest** [comment]
@gquerret 
`**/*.w` does the trick, thanks,
still struggling with 

exclude of  "/usr2/cce/build/schema/git/ccesmarttools/CceSmartTools/src/be/cce/ccetools/LegacyToolsUI/InfoViewer.cls"

current path entry is
```
    {
      "type": "source",
      "path": "git/ccesmarttools/CceSmartTools/src", 
      "excludes": "**/be/cce/ccetools/events/ShowDesktopAlert.cls,**/be/cce/ccetools/LegacyTools/**,**/be/cce/ccetools/LegacyToolsUi/**,**/*.w,**/*Control.cls,**/*Form.cls,be/cce/ccetools/SchemaInfoUI/**,be/cce/ccetools/winkit/**,be/cce/ccetools/base/**,cceinc/**,be/cce/ccetools/document/**,be/cce/ccetools/infragistics/**,be/cce/ccetools/ui/**,be/cce/dotnet/**,be/cce/ccetools/dotnet/**,be/cce/ccetools/mq/**,be/cce/SmartTools/Controls/**"
    },

```

For the build I use multiple excludesfile attributes.
I could put everything into a single file, or a file per path entry.

some snippets, from our build.xml
```
        <patternset id="compile.excludes">
            <exclude name="**/conv/**" />
            <exclude name="**/utils/**" />
            <exclude name="**/unittests/**" />
            <exclude name="**/cceinc/**" />
            <excludesfile name="${default.buildconfig}/exclude.lst" if="exclude.default.present" />
            <excludesfile name="${default.buildconfig}/exclude.${osname}.lst"
                if="exclude.default.os.present" />
            <excludesfile name="${custom.buildconfig}/exclude.lst" if="exclude.present" />
            <excludesfile name="${custom.buildconfig}/exclude.${phase}.lst"
                if="exclude.phase.present" />
            <excludesfile name="${custom.buildconfig}/exclude.${phase}.${osname}.lst"
                if="exclude.phase.os.present" />
            <excludesfile name="${custom.buildconfig}/exclude.${osname}.lst" if="exclude.os.present" />
            <excludesfile name="${buildinfodir}/cceprog_exclude.lst" if="exclude.cceprog.present" />
        </patternset>

       <patternset id="dontcompile_cw">
            <excludesfile name="${dont_compile.os.file}" />
        </patternset>

                <fileset dir="${project_SmartComponents}">
                    <patternset refid="smartcomponents.sources.smartcomponents" />
                    <patternset refid="compile.excludes" />
                    <patternset refid="dontcompile_cw" />
                </fileset>

```

**Comment by cverbiest** [comment]
struggle with exclude of "/usr2/cce/build/schema/git/ccesmarttools/CceSmartTools/src/be/cce/ccetools/LegacyToolsUI/InfoViewer.cls"solved, 

it's case sensitive exclude `be/cce/ccetools/LegacyToolsUÌ/**` works.

**Comment by gquerret** [comment]
Implemented in 1.4.25: New source directory properties: excludesFile and deployment

**Comment by Bert-CCE** [comment]
Is it possible that wildcards don't work when using excludesFile?
We have for instance 
```
Consultingwerk/Windows/**
``` 
but the sources underneath still get compiled. Specifying a full name works.

**Comment by gquerret** [comment]
The `excludes` attribute allows wildcards (case-sensitive), but they are not allowed in excludesFile attribute.
