### ISSUE TITLE
Include other extensions to re-compile after change in include

### ISSUE THREAD

**Issue by MarcelNewcold** [vscode-abl/vscode-abl#95]
Currently when you change something in a include file (with extentions .i) the plugin checks where this include is used and recompiles all these procedures.

As we also use other extentions than .i, (ex. .f for forms) can you make it optional to also include other extentions besides only .i

**Comment by gquerret** [comment]
* New attribute in `openedge-project.json`: `includeFileExtensions` (array of strings).
* Each extension has to be specified (no wildcard).
  * Defaults to `[".i"]` if not provided or empty. 
* Managed only at the language server level ; no syntax highlight / code completion for those additional extensions in VS Code, but saving one of those files will recompiled all procedures where it is referenced

**Comment by gquerret** [comment]
Will be included in next stable version

**Comment by gquerret** [comment]
Included in 1.4.25
