### ISSUE TITLE
Deprecated methods only appear so when using Javadoc style comments

### ISSUE THREAD

**Issue by kenherring-rkt** [vscode-abl/vscode-abl#97]
Looking at some deprecated methods in our code base and noticed that most don't show as such in the suggestions.  Two thoughts that I think would make this feature more useful for legacy codebases:

1.  Using the `@Deprecated.` annotation by itself has no effect.  Appears the [JsonDocumentation](https://github.com/Riverside-Software/pct/wiki/JsonDocumentation) function of PCT doesn't write a "comments" node in the JSON in this case, and for whatever reason this means VSCode doesn't see it.
2. Comments of the [StandardCommentBlock](https://github.com/Riverside-Software/pct/wiki/StandardCommentBlock) style don't get picked up.  I know these are really meant for the HTMLDocumentation, but perhaps they should be counted as Javadoc comments too since they're similar?  It would be a pain for us to update our whole codebase to change the comment style.  Adding an option to include the `/*----` style comments in Javadocs would be awesome.
    * The **StandardCommentBlock** is linked from **JsonDocumentation**, so it seems maybe there was some intention to include these at some point.

## Screenshot

Only `method4` shows as deprecated.  See the code below.  I'd really want to see methods2-5 all show as deprecated and only `method1` is not.

![image](https://github.com/vscode-abl/vscode-abl/assets/87667618/9ec1ef68-3603-4c2a-afba-2685d8ad4a0d)

## Sample Code

```abl
class testme.DeprecatedMethods :

  method public void method1 () :
    //No code - not deprecated
  end method.

  @Deprecated.
  method public void method2 () :
    //No code - deprecated but doesn't show as such in VSCode
  end method.

  @Deprecated(since="2023.09.01",message="testing deprecated method in VSCode").
  method public void method3 () :
    //No code - deprecated by doesn't show as such in VSCode
  end method.

  /**
  Purpose: test deprecation4
  */
  @Deprecated.
  method public void method4 () :
    //No code - this does show as deprecated because it has a JAVADOC style comment
  end method.

  /*------------------------------------------------------------------------------
    Purpose:
    Notes:
    @param parameter1 Description
    @return
    @deprecated
  ------------------------------------------------------------------------------*/
  @Deprecated.
  method public void method5 () :
    //No code - this does not show as deprecated because the StandardCommentBlock is not a JAVADOC style
  end method.

end class.

```

**Comment by gquerret** [comment]
I'll do some tests, thank you for raising the issue.

**Comment by kenherring-rkt** [comment]
Cool, thanks.  Let me know if you need more samples or anything.  I wrote up a bunch, but the ones I posted here get across the idea succinctly.

**Comment by gquerret** [comment]
Fixed !

**Comment by kenherring-rkt** [comment]
Looks great in the new version.  Thanks
