### ISSUE TITLE
Code completion for buffer definitions suggests fields

### ISSUE THREAD

**Issue by danielbecroft** [vscode-abl/vscode-abl#98]
Using: VSCode 1.82.2, plugin version v1.4.21
When defining a new buffer, the autocomplete suggests fields for the related table before the table name itself. 

```
define temp-table ttFoo no-undo
    field FooId as integer
    field FooName as charascter.

define buffer bttFoo for t|.
```

If the cursor is after the `for t` section, the autocomplete list contains (in order):

```
ttFoo.FooId
ttFoo
temp-table
_tt
```

This isn't too bad, but when the rest of the table name is typed (`ttFoo.`), the autocomplete suggests the first name, and "Enter" selects this, rather than putting a new line in:

```
define buffer bttFoo for ttFoo.
// auto-complete has ttFoo.FooId, hitting enter results in
define buffer bttFoo for ttFoo.FooId
```

The same applies to database tables. 

Update: This seems to be a general probelm with anything that requires a "buffer". I've tested the following:
* `CREATE`
* `DELETE`
* `FIND` (but not `FIND FIRST` or `FIND LAST`, interestingly)
* `DEFINE QUERY qttFoo FOR`

**Comment by danielbecroft** [comment]
The same issue occurs on `FIND` statements as well:

```
define temp-table ttFoo no-undo
    field FooId as integer
    field FooName as character.

find tt
```

The suggestions after the `find tt` option has:

```
ttFoo.FooId
ttFoo.FooName
ttFoo
```

The field options only go away once the entire buffer name has been typed.

**Comment by gquerret** [comment]
Confirmed, the `record` rule from the grammar is not handled correctly. That will be fixed in next version.

**Comment by gquerret** [comment]
Fixed in develop branch of LS
